// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 64c888a12aa3

package operations

import (
	"github.com/mollie/mollie-api-golang/models/components"
)

type CancelPayoutGlobals struct {
	// Most API credentials are specifically created for either live mode or test mode. In those cases the `testmode` query
	// parameter must not be sent. For organization-level credentials such as OAuth access tokens, you can enable test mode by
	// setting the `testmode` query parameter to `true`.
	//
	// Test entities cannot be retrieved when the endpoint is set to live mode, and vice versa.
	Testmode *bool `queryParam:"style=form,explode=true,name=testmode"`
}

func (c *CancelPayoutGlobals) GetTestmode() *bool {
	if c == nil {
		return nil
	}
	return c.Testmode
}

type CancelPayoutRequest struct {
	// Provide the ID of the payout.
	PayoutID string `pathParam:"style=simple,explode=false,name=payoutId"`
	// Most API credentials are specifically created for either live mode or test mode. In those cases the `testmode` query
	// parameter must not be sent. For organization-level credentials such as OAuth access tokens, you can enable test mode by
	// setting the `testmode` query parameter to `true`.
	//
	// Test entities cannot be retrieved when the endpoint is set to live mode, and vice versa.
	Testmode *bool `queryParam:"style=form,explode=true,name=testmode"`
	// A unique key to ensure idempotent requests. This key should be a UUID v4 string.
	IdempotencyKey *string `header:"style=simple,explode=false,name=idempotency-key"`
}

func (c *CancelPayoutRequest) GetPayoutID() string {
	if c == nil {
		return ""
	}
	return c.PayoutID
}

func (c *CancelPayoutRequest) GetTestmode() *bool {
	if c == nil {
		return nil
	}
	return c.Testmode
}

func (c *CancelPayoutRequest) GetIdempotencyKey() *string {
	if c == nil {
		return nil
	}
	return c.IdempotencyKey
}

type CancelPayoutResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The canceled payout object.
	EntityPayoutResponse *components.EntityPayoutResponse
}

func (c *CancelPayoutResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CancelPayoutResponse) GetEntityPayoutResponse() *components.EntityPayoutResponse {
	if c == nil {
		return nil
	}
	return c.EntityPayoutResponse
}
