// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/mollie/mollie-api-golang/models/components"
)

type CancelPaymentRequestBody struct {
	// Whether to create the entity in test mode or live mode.
	//
	// Most API credentials are specifically created for either live mode or test mode, in which case this parameter must
	// not be sent. For organization-level credentials such as OAuth access tokens, you can enable test mode by setting
	// `testmode` to `true`.
	Testmode *bool `json:"testmode,omitempty"`
}

func (c *CancelPaymentRequestBody) GetTestmode() *bool {
	if c == nil {
		return nil
	}
	return c.Testmode
}

type CancelPaymentRequest struct {
	// Provide the ID of the related payment.
	PaymentID string `pathParam:"style=simple,explode=false,name=paymentId"`
	// A unique key to ensure idempotent requests. This key should be a UUID v4 string.
	IdempotencyKey *string                   `header:"style=simple,explode=false,name=idempotency-key"`
	RequestBody    *CancelPaymentRequestBody `request:"mediaType=application/json"`
}

func (c *CancelPaymentRequest) GetPaymentID() string {
	if c == nil {
		return ""
	}
	return c.PaymentID
}

func (c *CancelPaymentRequest) GetIdempotencyKey() *string {
	if c == nil {
		return nil
	}
	return c.IdempotencyKey
}

func (c *CancelPaymentRequest) GetRequestBody() *CancelPaymentRequestBody {
	if c == nil {
		return nil
	}
	return c.RequestBody
}

type CancelPaymentResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The canceled payment object.
	PaymentResponse *components.PaymentResponse
}

func (c *CancelPaymentResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CancelPaymentResponse) GetPaymentResponse() *components.PaymentResponse {
	if c == nil {
		return nil
	}
	return c.PaymentResponse
}
