// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"errors"
	"fmt"
	"github.com/mollie/mollie-api-golang/internal/utils"
	"github.com/mollie/mollie-api-golang/models/components"
)

type CreateWebhookEventTypesType string

const (
	CreateWebhookEventTypesTypeArrayOfWebhookEventTypes CreateWebhookEventTypesType = "arrayOfWebhookEventTypes"
	CreateWebhookEventTypesTypeWebhookEventTypes        CreateWebhookEventTypesType = "webhook-event-types"
)

type CreateWebhookEventTypes struct {
	ArrayOfWebhookEventTypes []components.WebhookEventTypes `queryParam:"inline" union:"member"`
	WebhookEventTypes        *components.WebhookEventTypes  `queryParam:"inline" union:"member"`

	Type CreateWebhookEventTypesType
}

func CreateCreateWebhookEventTypesArrayOfWebhookEventTypes(arrayOfWebhookEventTypes []components.WebhookEventTypes) CreateWebhookEventTypes {
	typ := CreateWebhookEventTypesTypeArrayOfWebhookEventTypes

	return CreateWebhookEventTypes{
		ArrayOfWebhookEventTypes: arrayOfWebhookEventTypes,
		Type:                     typ,
	}
}

func CreateCreateWebhookEventTypesWebhookEventTypes(webhookEventTypes components.WebhookEventTypes) CreateWebhookEventTypes {
	typ := CreateWebhookEventTypesTypeWebhookEventTypes

	return CreateWebhookEventTypes{
		WebhookEventTypes: &webhookEventTypes,
		Type:              typ,
	}
}

func (u *CreateWebhookEventTypes) UnmarshalJSON(data []byte) error {

	var arrayOfWebhookEventTypes []components.WebhookEventTypes = []components.WebhookEventTypes{}
	if err := utils.UnmarshalJSON(data, &arrayOfWebhookEventTypes, "", true, nil); err == nil {
		u.ArrayOfWebhookEventTypes = arrayOfWebhookEventTypes
		u.Type = CreateWebhookEventTypesTypeArrayOfWebhookEventTypes
		return nil
	}

	var webhookEventTypes components.WebhookEventTypes = components.WebhookEventTypes("")
	if err := utils.UnmarshalJSON(data, &webhookEventTypes, "", true, nil); err == nil {
		u.WebhookEventTypes = &webhookEventTypes
		u.Type = CreateWebhookEventTypesTypeWebhookEventTypes
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for CreateWebhookEventTypes", string(data))
}

func (u CreateWebhookEventTypes) MarshalJSON() ([]byte, error) {
	if u.ArrayOfWebhookEventTypes != nil {
		return utils.MarshalJSON(u.ArrayOfWebhookEventTypes, "", true)
	}

	if u.WebhookEventTypes != nil {
		return utils.MarshalJSON(u.WebhookEventTypes, "", true)
	}

	return nil, errors.New("could not marshal union type CreateWebhookEventTypes: all fields are null")
}

type CreateWebhookRequestBody struct {
	// A name that identifies the webhook.
	Name string `json:"name"`
	// The URL Mollie will send the events to. This URL must be publicly accessible.
	URL        string                  `json:"url"`
	EventTypes CreateWebhookEventTypes `json:"eventTypes"`
	// Whether to create the entity in test mode or live mode.
	//
	// You can enable test mode by setting `testmode` to `true`.
	Testmode *bool `json:"testmode,omitempty"`
}

func (c *CreateWebhookRequestBody) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateWebhookRequestBody) GetURL() string {
	if c == nil {
		return ""
	}
	return c.URL
}

func (c *CreateWebhookRequestBody) GetEventTypes() CreateWebhookEventTypes {
	if c == nil {
		return CreateWebhookEventTypes{}
	}
	return c.EventTypes
}

func (c *CreateWebhookRequestBody) GetTestmode() *bool {
	if c == nil {
		return nil
	}
	return c.Testmode
}

type CreateWebhookRequest struct {
	// A unique key to ensure idempotent requests. This key should be a UUID v4 string.
	IdempotencyKey *string                   `header:"style=simple,explode=false,name=idempotency-key"`
	RequestBody    *CreateWebhookRequestBody `request:"mediaType=application/json"`
}

func (c *CreateWebhookRequest) GetIdempotencyKey() *string {
	if c == nil {
		return nil
	}
	return c.IdempotencyKey
}

func (c *CreateWebhookRequest) GetRequestBody() *CreateWebhookRequestBody {
	if c == nil {
		return nil
	}
	return c.RequestBody
}

type CreateWebhookResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The webhook object.
	CreateWebhook *components.CreateWebhook
}

func (c *CreateWebhookResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateWebhookResponse) GetCreateWebhook() *components.CreateWebhook {
	if c == nil {
		return nil
	}
	return c.CreateWebhook
}
