// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/mollie/mollie-api-golang/models/components"
)

type CreateClientLinkRequest struct {
	// A unique key to ensure idempotent requests. This key should be a UUID v4 string.
	IdempotencyKey    *string                       `header:"style=simple,explode=false,name=idempotency-key"`
	ClientLinkRequest *components.ClientLinkRequest `request:"mediaType=application/json"`
}

func (c *CreateClientLinkRequest) GetIdempotencyKey() *string {
	if c == nil {
		return nil
	}
	return c.IdempotencyKey
}

func (c *CreateClientLinkRequest) GetClientLinkRequest() *components.ClientLinkRequest {
	if c == nil {
		return nil
	}
	return c.ClientLinkRequest
}

type CreateClientLinkResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The newly created client link object.
	ClientLinkResponse *components.ClientLinkResponse
}

func (c *CreateClientLinkResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateClientLinkResponse) GetClientLinkResponse() *components.ClientLinkResponse {
	if c == nil {
		return nil
	}
	return c.ClientLinkResponse
}
