// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/mollie/mollie-api-golang/models/components"
)

type CreateCustomerPaymentRequest struct {
	// Provide the ID of the related customer.
	CustomerID string `pathParam:"style=simple,explode=false,name=customerId"`
	// A unique key to ensure idempotent requests. This key should be a UUID v4 string.
	IdempotencyKey *string                    `header:"style=simple,explode=false,name=idempotency-key"`
	PaymentRequest *components.PaymentRequest `request:"mediaType=application/json"`
}

func (c *CreateCustomerPaymentRequest) GetCustomerID() string {
	if c == nil {
		return ""
	}
	return c.CustomerID
}

func (c *CreateCustomerPaymentRequest) GetIdempotencyKey() *string {
	if c == nil {
		return nil
	}
	return c.IdempotencyKey
}

func (c *CreateCustomerPaymentRequest) GetPaymentRequest() *components.PaymentRequest {
	if c == nil {
		return nil
	}
	return c.PaymentRequest
}

type CreateCustomerPaymentResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The newly created payment object.
	PaymentResponse *components.PaymentResponse
}

func (c *CreateCustomerPaymentResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateCustomerPaymentResponse) GetPaymentResponse() *components.PaymentResponse {
	if c == nil {
		return nil
	}
	return c.PaymentResponse
}
