// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/mollie/mollie-api-golang/models/components"
)

type CreateCustomerRequest struct {
	// A unique key to ensure idempotent requests. This key should be a UUID v4 string.
	IdempotencyKey *string                    `header:"style=simple,explode=false,name=idempotency-key"`
	EntityCustomer *components.EntityCustomer `request:"mediaType=application/json"`
}

func (c *CreateCustomerRequest) GetIdempotencyKey() *string {
	if c == nil {
		return nil
	}
	return c.IdempotencyKey
}

func (c *CreateCustomerRequest) GetEntityCustomer() *components.EntityCustomer {
	if c == nil {
		return nil
	}
	return c.EntityCustomer
}

type CreateCustomerResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The newly created customer object.
	CustomerResponse *components.CustomerResponse
}

func (c *CreateCustomerResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateCustomerResponse) GetCustomerResponse() *components.CustomerResponse {
	if c == nil {
		return nil
	}
	return c.CustomerResponse
}
