// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/mollie/mollie-api-golang/models/components"
)

type CreateWebhookRequest struct {
	// A name that identifies the webhook.
	Name string `json:"name"`
	// The URL Mollie will send the events to. This URL must be publicly accessible.
	URL string `json:"url"`
	// The event's type
	WebhookEventTypes components.WebhookEventTypes `json:"eventTypes"`
	// Whether to create the entity in test mode or live mode.
	//
	// Most API credentials are specifically created for either live mode or test mode, in which case this parameter can be
	// omitted. For organization-level credentials such as OAuth access tokens, you can enable test mode by setting
	// `testmode` to `true`.
	Testmode *bool `json:"testmode,omitempty"`
}

func (o *CreateWebhookRequest) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *CreateWebhookRequest) GetURL() string {
	if o == nil {
		return ""
	}
	return o.URL
}

func (o *CreateWebhookRequest) GetWebhookEventTypes() components.WebhookEventTypes {
	if o == nil {
		return components.WebhookEventTypes("")
	}
	return o.WebhookEventTypes
}

func (o *CreateWebhookRequest) GetTestmode() *bool {
	if o == nil {
		return nil
	}
	return o.Testmode
}

type CreateWebhookResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The webhook object.
	CreateWebhook *components.CreateWebhook
}

func (o *CreateWebhookResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateWebhookResponse) GetCreateWebhook() *components.CreateWebhook {
	if o == nil {
		return nil
	}
	return o.CreateWebhook
}
