// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/mollie/mollie-api-golang/models/components"
)

type DeleteWebhookRequestBody struct {
	// Most API credentials are specifically created for either live mode or test mode. For organization-level credentials
	// such as OAuth access tokens, you can enable test mode by setting `testmode` to `true`.
	//
	// Test entities cannot be retrieved when the endpoint is set to live mode, and vice versa.
	Testmode *bool `json:"testmode,omitempty"`
}

func (o *DeleteWebhookRequestBody) GetTestmode() *bool {
	if o == nil {
		return nil
	}
	return o.Testmode
}

type DeleteWebhookRequest struct {
	// Provide the ID of the item you want to perform this operation on.
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// A unique key to ensure idempotent requests. This key should be a UUID v4 string.
	IdempotencyKey *string                   `header:"style=simple,explode=false,name=idempotency-key"`
	RequestBody    *DeleteWebhookRequestBody `request:"mediaType=application/json"`
}

func (o *DeleteWebhookRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *DeleteWebhookRequest) GetIdempotencyKey() *string {
	if o == nil {
		return nil
	}
	return o.IdempotencyKey
}

func (o *DeleteWebhookRequest) GetRequestBody() *DeleteWebhookRequestBody {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

type DeleteWebhookResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// No content.
	Any any
}

func (o *DeleteWebhookResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *DeleteWebhookResponse) GetAny() any {
	if o == nil {
		return nil
	}
	return o.Any
}
