// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/mollie/mollie-api-golang/models/components"
)

type DeleteProfileRequest struct {
	// Provide the ID of the item you want to perform this operation on.
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// A unique key to ensure idempotent requests. This key should be a UUID v4 string.
	IdempotencyKey *string `header:"style=simple,explode=false,name=idempotency-key"`
}

func (d *DeleteProfileRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

func (d *DeleteProfileRequest) GetIdempotencyKey() *string {
	if d == nil {
		return nil
	}
	return d.IdempotencyKey
}

type DeleteProfileResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// An empty response.
	Any any
}

func (d *DeleteProfileResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteProfileResponse) GetAny() any {
	if d == nil {
		return nil
	}
	return d.Any
}
