// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/mollie/mollie-api-golang/models/components"
)

type DeletePaymentLinkRequestBody struct {
	// Most API credentials are specifically created for either live mode or test mode. For organization-level credentials
	// such as OAuth access tokens, you can enable test mode by setting `testmode` to `true`.
	//
	// Test entities cannot be retrieved when the endpoint is set to live mode, and vice versa.
	Testmode *bool `json:"testmode,omitempty"`
}

func (o *DeletePaymentLinkRequestBody) GetTestmode() *bool {
	if o == nil {
		return nil
	}
	return o.Testmode
}

type DeletePaymentLinkRequest struct {
	// Provide the ID of the related payment link.
	PaymentLinkID string                        `pathParam:"style=simple,explode=false,name=paymentLinkId"`
	RequestBody   *DeletePaymentLinkRequestBody `request:"mediaType=application/json"`
}

func (o *DeletePaymentLinkRequest) GetPaymentLinkID() string {
	if o == nil {
		return ""
	}
	return o.PaymentLinkID
}

func (o *DeletePaymentLinkRequest) GetRequestBody() *DeletePaymentLinkRequestBody {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

type DeletePaymentLinkResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// An empty response.
	Any any
}

func (o *DeletePaymentLinkResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *DeletePaymentLinkResponse) GetAny() any {
	if o == nil {
		return nil
	}
	return o.Any
}
