// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 1a9d057f07b7

package operations

import (
	"github.com/mollie/mollie-api-golang/models/components"
)

type DisableMethodIssuerRequest struct {
	// Provide the ID of the related profile.
	ProfileID string `pathParam:"style=simple,explode=false,name=profileId"`
	// Provide the ID of the related payment method.
	MethodID components.MethodIDWithIssuer `pathParam:"style=simple,explode=false,name=methodId"`
	// Provide the ID of the related issuer.
	IssuerID string `pathParam:"style=simple,explode=false,name=issuerId"`
	// A unique key to ensure idempotent requests. This key should be a UUID v4 string.
	IdempotencyKey *string `header:"style=simple,explode=false,name=idempotency-key"`
}

func (d *DisableMethodIssuerRequest) GetProfileID() string {
	if d == nil {
		return ""
	}
	return d.ProfileID
}

func (d *DisableMethodIssuerRequest) GetMethodID() components.MethodIDWithIssuer {
	if d == nil {
		return components.MethodIDWithIssuer("")
	}
	return d.MethodID
}

func (d *DisableMethodIssuerRequest) GetIssuerID() string {
	if d == nil {
		return ""
	}
	return d.IssuerID
}

func (d *DisableMethodIssuerRequest) GetIdempotencyKey() *string {
	if d == nil {
		return nil
	}
	return d.IdempotencyKey
}

type DisableMethodIssuerResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (d *DisableMethodIssuerResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}
