// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/mollie/mollie-api-golang/models/components"
)

type GetInvoiceRequest struct {
	// Provide the ID of the item you want to perform this operation on.
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetInvoiceRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type GetInvoiceResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The invoice object.
	EntityInvoice *components.EntityInvoice
}

func (o *GetInvoiceResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetInvoiceResponse) GetEntityInvoice() *components.EntityInvoice {
	if o == nil {
		return nil
	}
	return o.EntityInvoice
}
