// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/mollie/mollie-api-golang/models/components"
)

type GetOnboardingStatusRequest struct {
	// A unique key to ensure idempotent requests. This key should be a UUID v4 string.
	IdempotencyKey *string `header:"style=simple,explode=false,name=idempotency-key"`
}

func (o *GetOnboardingStatusRequest) GetIdempotencyKey() *string {
	if o == nil {
		return nil
	}
	return o.IdempotencyKey
}

type GetOnboardingStatusResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The onboarding status object of the current organization.
	EntityOnboardingStatus *components.EntityOnboardingStatus
}

func (o *GetOnboardingStatusResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetOnboardingStatusResponse) GetEntityOnboardingStatus() *components.EntityOnboardingStatus {
	if o == nil {
		return nil
	}
	return o.EntityOnboardingStatus
}
