// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/mollie/mollie-api-golang/models/components"
)

type GetPermissionRequest struct {
	// Provide the ID of the related permission.
	PermissionID string `pathParam:"style=simple,explode=false,name=permissionId"`
	// Most API credentials are specifically created for either live mode or test mode. In those cases the `testmode` query
	// parameter can be omitted. For organization-level credentials such as OAuth access tokens, you can enable test mode by
	// setting the `testmode` query parameter to `true`.
	//
	// Test entities cannot be retrieved when the endpoint is set to live mode, and vice versa.
	Testmode *bool `queryParam:"style=form,explode=true,name=testmode"`
	// A unique key to ensure idempotent requests. This key should be a UUID v4 string.
	IdempotencyKey *string `header:"style=simple,explode=false,name=idempotency-key"`
}

func (g *GetPermissionRequest) GetPermissionID() string {
	if g == nil {
		return ""
	}
	return g.PermissionID
}

func (g *GetPermissionRequest) GetTestmode() *bool {
	if g == nil {
		return nil
	}
	return g.Testmode
}

func (g *GetPermissionRequest) GetIdempotencyKey() *string {
	if g == nil {
		return nil
	}
	return g.IdempotencyKey
}

type GetPermissionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The permission object.
	EntityPermission *components.EntityPermission
}

func (g *GetPermissionResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetPermissionResponse) GetEntityPermission() *components.EntityPermission {
	if g == nil {
		return nil
	}
	return g.EntityPermission
}
