// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/mollie/mollie-api-golang/models/components"
)

type GetPrimaryBalanceResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The primary balance object.
	EntityBalance *components.EntityBalance
}

func (o *GetPrimaryBalanceResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetPrimaryBalanceResponse) GetEntityBalance() *components.EntityBalance {
	if o == nil {
		return nil
	}
	return o.EntityBalance
}
