// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/mollie/mollie-api-golang/models/components"
)

type GetTerminalRequest struct {
	// Provide the ID of the related terminal.
	TerminalID string `pathParam:"style=simple,explode=false,name=terminalId"`
	// Most API credentials are specifically created for either live mode or test mode. In those cases the `testmode` query
	// parameter can be omitted. For organization-level credentials such as OAuth access tokens, you can enable test mode by
	// setting the `testmode` query parameter to `true`.
	//
	// Test entities cannot be retrieved when the endpoint is set to live mode, and vice versa.
	Testmode *bool `queryParam:"style=form,explode=true,name=testmode"`
}

func (o *GetTerminalRequest) GetTerminalID() string {
	if o == nil {
		return ""
	}
	return o.TerminalID
}

func (o *GetTerminalRequest) GetTestmode() *bool {
	if o == nil {
		return nil
	}
	return o.Testmode
}

type GetTerminalResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The terminal object.
	EntityTerminal *components.EntityTerminal
}

func (o *GetTerminalResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetTerminalResponse) GetEntityTerminal() *components.EntityTerminal {
	if o == nil {
		return nil
	}
	return o.EntityTerminal
}
