// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/mollie/mollie-api-golang/models/components"
)

type GetWebhookEventGlobals struct {
	// Most API credentials are specifically created for either live mode or test mode. In those cases the `testmode` query
	// parameter can be omitted. For organization-level credentials such as OAuth access tokens, you can enable test mode by
	// setting the `testmode` query parameter to `true`.
	//
	// Test entities cannot be retrieved when the endpoint is set to live mode, and vice versa.
	Testmode *bool `queryParam:"style=form,explode=true,name=testmode"`
}

func (g *GetWebhookEventGlobals) GetTestmode() *bool {
	if g == nil {
		return nil
	}
	return g.Testmode
}

type GetWebhookEventRequest struct {
	// Provide the ID of the item you want to perform this operation on.
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Most API credentials are specifically created for either live mode or test mode. In those cases the `testmode` query
	// parameter can be omitted. For organization-level credentials such as OAuth access tokens, you can enable test mode by
	// setting the `testmode` query parameter to `true`.
	//
	// Test entities cannot be retrieved when the endpoint is set to live mode, and vice versa.
	Testmode *bool `queryParam:"style=form,explode=true,name=testmode"`
	// A unique key to ensure idempotent requests. This key should be a UUID v4 string.
	IdempotencyKey *string `header:"style=simple,explode=false,name=idempotency-key"`
}

func (g *GetWebhookEventRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetWebhookEventRequest) GetTestmode() *bool {
	if g == nil {
		return nil
	}
	return g.Testmode
}

func (g *GetWebhookEventRequest) GetIdempotencyKey() *string {
	if g == nil {
		return nil
	}
	return g.IdempotencyKey
}

type GetWebhookEventResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The webhook event object.
	EntityWebhookEvent *components.EntityWebhookEvent
}

func (g *GetWebhookEventResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetWebhookEventResponse) GetEntityWebhookEvent() *components.EntityWebhookEvent {
	if g == nil {
		return nil
	}
	return g.EntityWebhookEvent
}
