// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/mollie/mollie-api-golang/models/components"
)

type ListConnectBalanceTransfersGlobals struct {
	// Most API credentials are specifically created for either live mode or test mode. In those cases the `testmode` query
	// parameter must not be sent. For organization-level credentials such as OAuth access tokens, you can enable test mode by
	// setting the `testmode` query parameter to `true`.
	//
	// Test entities cannot be retrieved when the endpoint is set to live mode, and vice versa.
	Testmode *bool `queryParam:"style=form,explode=true,name=testmode"`
}

func (l *ListConnectBalanceTransfersGlobals) GetTestmode() *bool {
	if l == nil {
		return nil
	}
	return l.Testmode
}

type ListConnectBalanceTransfersRequest struct {
	// Provide an ID to start the result set from the item with the given ID and onwards. This allows you to paginate the
	// result set.
	From *string `queryParam:"style=form,explode=true,name=from"`
	// The maximum number of items to return. Defaults to 50 items.
	Limit *int64 `queryParam:"style=form,explode=true,name=limit"`
	// Used for setting the direction of the result set. Defaults to descending order, meaning the results are ordered from
	// newest to oldest.
	Sort *components.Sorting `queryParam:"style=form,explode=true,name=sort"`
	// You can enable test mode by setting the `testmode` query parameter to `true`.
	//
	// Test entities cannot be retrieved when the endpoint is set to live mode, and vice versa.
	Testmode *bool `queryParam:"style=form,explode=true,name=testmode"`
	// A unique key to ensure idempotent requests. This key should be a UUID v4 string.
	IdempotencyKey *string `header:"style=simple,explode=false,name=idempotency-key"`
}

func (l *ListConnectBalanceTransfersRequest) GetFrom() *string {
	if l == nil {
		return nil
	}
	return l.From
}

func (l *ListConnectBalanceTransfersRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListConnectBalanceTransfersRequest) GetSort() *components.Sorting {
	if l == nil {
		return nil
	}
	return l.Sort
}

func (l *ListConnectBalanceTransfersRequest) GetTestmode() *bool {
	if l == nil {
		return nil
	}
	return l.Testmode
}

func (l *ListConnectBalanceTransfersRequest) GetIdempotencyKey() *string {
	if l == nil {
		return nil
	}
	return l.IdempotencyKey
}

type ListConnectBalanceTransfersEmbedded struct {
	// A list of Connect balance transfers.
	ConnectBalanceTransfers []components.EntityBalanceTransferResponse `json:"connect_balance_transfers"`
}

func (l *ListConnectBalanceTransfersEmbedded) GetConnectBalanceTransfers() []components.EntityBalanceTransferResponse {
	if l == nil {
		return []components.EntityBalanceTransferResponse{}
	}
	return l.ConnectBalanceTransfers
}

// ListConnectBalanceTransfersResponseBody - A list of Connect balance transfers. For a complete reference of the Connect balance transfer
// object, refer to the [Get balance transfer endpoint](get-balance-transfer) documentation.
type ListConnectBalanceTransfersResponseBody struct {
	// The number of items in this result set. If more items are available, a `_links.next` URL will be present in the result
	// as well.
	//
	// The maximum number of items per result set is controlled by the `limit` property provided in the request. The default
	// limit is 50 items.
	Count    int64                               `json:"count"`
	Embedded ListConnectBalanceTransfersEmbedded `json:"_embedded"`
	// Links to help navigate through the lists of items. Every URL object will contain an `href` and a `type` field.
	Links components.ListLinks `json:"_links"`
}

func (l *ListConnectBalanceTransfersResponseBody) GetCount() int64 {
	if l == nil {
		return 0
	}
	return l.Count
}

func (l *ListConnectBalanceTransfersResponseBody) GetEmbedded() ListConnectBalanceTransfersEmbedded {
	if l == nil {
		return ListConnectBalanceTransfersEmbedded{}
	}
	return l.Embedded
}

func (l *ListConnectBalanceTransfersResponseBody) GetLinks() components.ListLinks {
	if l == nil {
		return components.ListLinks{}
	}
	return l.Links
}

type ListConnectBalanceTransfersResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A list of Connect balance transfers. For a complete reference of the Connect balance transfer
	// object, refer to the [Get balance transfer endpoint](get-balance-transfer) documentation.
	Object *ListConnectBalanceTransfersResponseBody
}

func (l *ListConnectBalanceTransfersResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListConnectBalanceTransfersResponse) GetObject() *ListConnectBalanceTransfersResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
