// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/mollie/mollie-api-golang/models/components"
)

type ListCapabilitiesRequest struct {
	// A unique key to ensure idempotent requests. This key should be a UUID v4 string.
	IdempotencyKey *string `header:"style=simple,explode=false,name=idempotency-key"`
}

func (l *ListCapabilitiesRequest) GetIdempotencyKey() *string {
	if l == nil {
		return nil
	}
	return l.IdempotencyKey
}

type ListCapabilitiesEmbedded struct {
	Capabilities []components.EntityCapability `json:"capabilities"`
}

func (l *ListCapabilitiesEmbedded) GetCapabilities() []components.EntityCapability {
	if l == nil {
		return []components.EntityCapability{}
	}
	return l.Capabilities
}

type ListCapabilitiesLinks struct {
	// In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
	Documentation *components.URLObj `json:"documentation,omitempty"`
}

func (l *ListCapabilitiesLinks) GetDocumentation() *components.URLObj {
	if l == nil {
		return nil
	}
	return l.Documentation
}

// ListCapabilitiesResponseBody - A list of capabilities.
type ListCapabilitiesResponseBody struct {
	// The number of items in this result set.
	Count    int64                    `json:"count"`
	Embedded ListCapabilitiesEmbedded `json:"_embedded"`
	Links    ListCapabilitiesLinks    `json:"_links"`
}

func (l *ListCapabilitiesResponseBody) GetCount() int64 {
	if l == nil {
		return 0
	}
	return l.Count
}

func (l *ListCapabilitiesResponseBody) GetEmbedded() ListCapabilitiesEmbedded {
	if l == nil {
		return ListCapabilitiesEmbedded{}
	}
	return l.Embedded
}

func (l *ListCapabilitiesResponseBody) GetLinks() ListCapabilitiesLinks {
	if l == nil {
		return ListCapabilitiesLinks{}
	}
	return l.Links
}

type ListCapabilitiesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A list of capabilities.
	Object *ListCapabilitiesResponseBody
}

func (l *ListCapabilitiesResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListCapabilitiesResponse) GetObject() *ListCapabilitiesResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
