// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/mollie/mollie-api-golang/models/components"
)

type ListBalanceTransactionsGlobals struct {
	// Most API credentials are specifically created for either live mode or test mode. In those cases the `testmode` query
	// parameter must not be sent. For organization-level credentials such as OAuth access tokens, you can enable test mode by
	// setting the `testmode` query parameter to `true`.
	//
	// Test entities cannot be retrieved when the endpoint is set to live mode, and vice versa.
	Testmode *bool `queryParam:"style=form,explode=true,name=testmode"`
}

func (l *ListBalanceTransactionsGlobals) GetTestmode() *bool {
	if l == nil {
		return nil
	}
	return l.Testmode
}

type ListBalanceTransactionsRequest struct {
	// Provide the ID of the related balance.
	BalanceID string `pathParam:"style=simple,explode=false,name=balanceId"`
	// Provide an ID to start the result set from the item with the given ID and onwards. This allows you to paginate the
	// result set.
	From *string `queryParam:"style=form,explode=true,name=from"`
	// The maximum number of items to return. Defaults to 50 items.
	Limit *int64 `queryParam:"style=form,explode=true,name=limit"`
	// You can enable test mode by setting the `testmode` query parameter to `true`.
	//
	// Test entities cannot be retrieved when the endpoint is set to live mode, and vice versa.
	Testmode *bool `queryParam:"style=form,explode=true,name=testmode"`
	// A unique key to ensure idempotent requests. This key should be a UUID v4 string.
	IdempotencyKey *string `header:"style=simple,explode=false,name=idempotency-key"`
}

func (l *ListBalanceTransactionsRequest) GetBalanceID() string {
	if l == nil {
		return ""
	}
	return l.BalanceID
}

func (l *ListBalanceTransactionsRequest) GetFrom() *string {
	if l == nil {
		return nil
	}
	return l.From
}

func (l *ListBalanceTransactionsRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListBalanceTransactionsRequest) GetTestmode() *bool {
	if l == nil {
		return nil
	}
	return l.Testmode
}

func (l *ListBalanceTransactionsRequest) GetIdempotencyKey() *string {
	if l == nil {
		return nil
	}
	return l.IdempotencyKey
}

type ListBalanceTransactionsEmbedded struct {
	// An array of balance transaction objects.
	BalanceTransactions []components.EntityBalanceTransaction `json:"balance_transactions"`
}

func (l *ListBalanceTransactionsEmbedded) GetBalanceTransactions() []components.EntityBalanceTransaction {
	if l == nil {
		return []components.EntityBalanceTransaction{}
	}
	return l.BalanceTransactions
}

// ListBalanceTransactionsResponseBody - A list of balance transaction objects.
type ListBalanceTransactionsResponseBody struct {
	// The number of items in this result set. If more items are available, a `_links.next` URL will be present in the result
	// as well.
	//
	// The maximum number of items per result set is controlled by the `limit` property provided in the request. The default
	// limit is 50 items.
	Count    int64                           `json:"count"`
	Embedded ListBalanceTransactionsEmbedded `json:"_embedded"`
	// Links to help navigate through the lists of items. Every URL object will contain an `href` and a `type` field.
	Links components.ListLinks `json:"_links"`
}

func (l *ListBalanceTransactionsResponseBody) GetCount() int64 {
	if l == nil {
		return 0
	}
	return l.Count
}

func (l *ListBalanceTransactionsResponseBody) GetEmbedded() ListBalanceTransactionsEmbedded {
	if l == nil {
		return ListBalanceTransactionsEmbedded{}
	}
	return l.Embedded
}

func (l *ListBalanceTransactionsResponseBody) GetLinks() components.ListLinks {
	if l == nil {
		return components.ListLinks{}
	}
	return l.Links
}

type ListBalanceTransactionsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A list of balance transaction objects.
	Object *ListBalanceTransactionsResponseBody

	Next func() (*ListBalanceTransactionsResponse, error)
}

func (l *ListBalanceTransactionsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListBalanceTransactionsResponse) GetObject() *ListBalanceTransactionsResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
