// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/mollie/mollie-api-golang/models/components"
)

type ListInvoicesRequest struct {
	// Filter for an invoice with a specific invoice reference, for example
	// `2024.10000`.
	Reference *string `queryParam:"style=form,explode=true,name=reference"`
	// Filter for invoices of a specific year, for example `2024`.
	Year *string `queryParam:"style=form,explode=true,name=year"`
	// Filter for invoices of a specific month, for example `01`.
	Month *string `queryParam:"style=form,explode=true,name=month"`
	// Provide an ID to start the result set from the item with the given ID and onwards. This allows you to paginate the
	// result set.
	From *string `queryParam:"style=form,explode=true,name=from"`
	// The maximum number of items to return. Defaults to 50 items.
	Limit *int64 `queryParam:"style=form,explode=true,name=limit"`
	// Used for setting the direction of the result set. Defaults to descending order, meaning the results are ordered from
	// newest to oldest.
	Sort *components.ListSort `queryParam:"style=form,explode=true,name=sort"`
}

func (o *ListInvoicesRequest) GetReference() *string {
	if o == nil {
		return nil
	}
	return o.Reference
}

func (o *ListInvoicesRequest) GetYear() *string {
	if o == nil {
		return nil
	}
	return o.Year
}

func (o *ListInvoicesRequest) GetMonth() *string {
	if o == nil {
		return nil
	}
	return o.Month
}

func (o *ListInvoicesRequest) GetFrom() *string {
	if o == nil {
		return nil
	}
	return o.From
}

func (o *ListInvoicesRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *ListInvoicesRequest) GetSort() *components.ListSort {
	if o == nil {
		return nil
	}
	return o.Sort
}

type Invoice struct {
}

type ListInvoicesEmbedded struct {
	// An array of invoice objects. For a complete reference of
	// the invoice object, refer to the [Get invoice endpoint](get-invoice) documentation.
	Invoices []Invoice `json:"invoices,omitempty"`
}

func (o *ListInvoicesEmbedded) GetInvoices() []Invoice {
	if o == nil {
		return nil
	}
	return o.Invoices
}

// ListInvoicesResponseBody - A list of invoice objects. For a complete reference of the invoice
// object, refer to the [Get invoice endpoint](get-invoice) documentation.
type ListInvoicesResponseBody struct {
	// The number of items in this result set. If more items are available, a `_links.next` URL will be present in the result
	// as well.
	//
	// The maximum number of items per result set is controlled by the `limit` property provided in the request. The default
	// limit is 50 items.
	Count    *int64                `json:"count,omitempty"`
	Embedded *ListInvoicesEmbedded `json:"_embedded,omitempty"`
	// Links to help navigate through the lists of items. Every URL object will contain an `href` and a `type` field.
	Links *components.ListLinks `json:"_links,omitempty"`
}

func (o *ListInvoicesResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *ListInvoicesResponseBody) GetEmbedded() *ListInvoicesEmbedded {
	if o == nil {
		return nil
	}
	return o.Embedded
}

func (o *ListInvoicesResponseBody) GetLinks() *components.ListLinks {
	if o == nil {
		return nil
	}
	return o.Links
}

type ListInvoicesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A list of invoice objects. For a complete reference of the invoice
	// object, refer to the [Get invoice endpoint](get-invoice) documentation.
	Object *ListInvoicesResponseBody
}

func (o *ListInvoicesResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListInvoicesResponse) GetObject() *ListInvoicesResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
