// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/mollie/mollie-api-golang/models/components"
)

type PaymentCreateRouteRequest struct {
	// Provide the ID of the related payment.
	PaymentID string `pathParam:"style=simple,explode=false,name=paymentId"`
	// A unique key to ensure idempotent requests. This key should be a UUID v4 string.
	IdempotencyKey     *string                        `header:"style=simple,explode=false,name=idempotency-key"`
	RouteCreateRequest *components.RouteCreateRequest `request:"mediaType=application/json"`
}

func (p *PaymentCreateRouteRequest) GetPaymentID() string {
	if p == nil {
		return ""
	}
	return p.PaymentID
}

func (p *PaymentCreateRouteRequest) GetIdempotencyKey() *string {
	if p == nil {
		return nil
	}
	return p.IdempotencyKey
}

func (p *PaymentCreateRouteRequest) GetRouteCreateRequest() *components.RouteCreateRequest {
	if p == nil {
		return nil
	}
	return p.RouteCreateRequest
}

type PaymentCreateRouteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The route object.
	RouteCreateResponse *components.RouteCreateResponse
}

func (p *PaymentCreateRouteResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PaymentCreateRouteResponse) GetRouteCreateResponse() *components.RouteCreateResponse {
	if p == nil {
		return nil
	}
	return p.RouteCreateResponse
}
