// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type BalanceCardRegion string

const (
	BalanceCardRegionIntraEea BalanceCardRegion = "intra-eea"
	BalanceCardRegionIntraEu  BalanceCardRegion = "intra-eu"
	BalanceCardRegionDomestic BalanceCardRegion = "domestic"
	BalanceCardRegionOther    BalanceCardRegion = "other"
)

func (e BalanceCardRegion) ToPointer() *BalanceCardRegion {
	return &e
}
