// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// BalanceTransferStatus - The status of the transfer.
type BalanceTransferStatus string

const (
	BalanceTransferStatusCreated   BalanceTransferStatus = "created"
	BalanceTransferStatusFailed    BalanceTransferStatus = "failed"
	BalanceTransferStatusSucceeded BalanceTransferStatus = "succeeded"
)

func (e BalanceTransferStatus) ToPointer() *BalanceTransferStatus {
	return &e
}
