// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CapabilityStatus string

const (
	CapabilityStatusUnrequested CapabilityStatus = "unrequested"
	CapabilityStatusEnabled     CapabilityStatus = "enabled"
	CapabilityStatusDisabled    CapabilityStatus = "disabled"
	CapabilityStatusPending     CapabilityStatus = "pending"
)

func (e CapabilityStatus) ToPointer() *CapabilityStatus {
	return &e
}
