// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// CapabilityRequirementStatus - The status of the requirement depends on its due date.
// If no due date is given, the status will be `requested`.
type CapabilityRequirementStatus string

const (
	CapabilityRequirementStatusCurrentlyDue CapabilityRequirementStatus = "currently-due"
	CapabilityRequirementStatusPastDue      CapabilityRequirementStatus = "past-due"
	CapabilityRequirementStatusRequested    CapabilityRequirementStatus = "requested"
)

func (e CapabilityRequirementStatus) ToPointer() *CapabilityRequirementStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *CapabilityRequirementStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "currently-due", "past-due", "requested":
			return true
		}
	}
	return false
}
