// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 9bb0b356b8fc

package components

import (
	"encoding/json"
	"fmt"
)

// DraftTransferStatus - The status of the draft transfer.
type DraftTransferStatus string

const (
	DraftTransferStatusAwaitingInitiation DraftTransferStatus = "awaiting-initiation"
	DraftTransferStatusInitiated          DraftTransferStatus = "initiated"
	DraftTransferStatusDeclined           DraftTransferStatus = "declined"
)

func (e DraftTransferStatus) ToPointer() *DraftTransferStatus {
	return &e
}
func (e *DraftTransferStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "awaiting-initiation":
		fallthrough
	case "initiated":
		fallthrough
	case "declined":
		*e = DraftTransferStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DraftTransferStatus: %v", v)
	}
}
