// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// EntityInvoiceStatus - Status of the invoice.
//
// * `open` — The invoice is not paid yet.
// * `paid` — The invoice is paid.
// * `overdue` — Payment of the invoice is overdue.
type EntityInvoiceStatus string

const (
	EntityInvoiceStatusOpen    EntityInvoiceStatus = "open"
	EntityInvoiceStatusPaid    EntityInvoiceStatus = "paid"
	EntityInvoiceStatusOverdue EntityInvoiceStatus = "overdue"
)

func (e EntityInvoiceStatus) ToPointer() *EntityInvoiceStatus {
	return &e
}
func (e *EntityInvoiceStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "open":
		fallthrough
	case "paid":
		fallthrough
	case "overdue":
		*e = EntityInvoiceStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EntityInvoiceStatus: %v", v)
	}
}

type EntityInvoiceLine struct {
	// The administrative period in `YYYY-MM` on which the line should be booked.
	Period *string `json:"period,omitempty"`
	// Description of the product.
	Description *string `json:"description,omitempty"`
	// Number of products invoiced. For example, the number of payments.
	Count *int64 `json:"count,omitempty"`
	// VAT percentage rate that applies to this product.
	VatPercentage *int64 `json:"vatPercentage,omitempty"`
	// In v2 endpoints, monetary amounts are represented as objects with a `currency` and `value` field.
	Amount *Amount `json:"amount,omitempty"`
}

func (o *EntityInvoiceLine) GetPeriod() *string {
	if o == nil {
		return nil
	}
	return o.Period
}

func (o *EntityInvoiceLine) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *EntityInvoiceLine) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *EntityInvoiceLine) GetVatPercentage() *int64 {
	if o == nil {
		return nil
	}
	return o.VatPercentage
}

func (o *EntityInvoiceLine) GetAmount() *Amount {
	if o == nil {
		return nil
	}
	return o.Amount
}

// EntityInvoiceLinks - An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
type EntityInvoiceLinks struct {
	// In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
	Self *URLObj `json:"self,omitempty"`
	// In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
	Pdf *URLObj `json:"pdf,omitempty"`
	// In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
	Documentation *URLObj `json:"documentation,omitempty"`
}

func (o *EntityInvoiceLinks) GetSelf() *URLObj {
	if o == nil {
		return nil
	}
	return o.Self
}

func (o *EntityInvoiceLinks) GetPdf() *URLObj {
	if o == nil {
		return nil
	}
	return o.Pdf
}

func (o *EntityInvoiceLinks) GetDocumentation() *URLObj {
	if o == nil {
		return nil
	}
	return o.Documentation
}

type EntityInvoice struct {
	// Indicates that the response contains an invoice object.
	// Will always contain the string `invoice` for this endpoint.
	Resource *string `json:"resource,omitempty"`
	// The identifier uniquely referring to this invoice. Example: `inv_FrvewDA3Pr`.
	ID *string `json:"id,omitempty"`
	// The reference number of the invoice. An example value would be: `2024.10000`.
	Reference *string `json:"reference,omitempty"`
	// The VAT number to which the invoice was issued to, if applicable.
	VatNumber *string `json:"vatNumber,omitempty"`
	// Status of the invoice.
	//
	// * `open` — The invoice is not paid yet.
	// * `paid` — The invoice is paid.
	// * `overdue` — Payment of the invoice is overdue.
	Status *EntityInvoiceStatus `json:"status,omitempty"`
	// In v2 endpoints, monetary amounts are represented as objects with a `currency` and `value` field.
	NetAmount *Amount `json:"netAmount,omitempty"`
	// In v2 endpoints, monetary amounts are represented as objects with a `currency` and `value` field.
	VatAmount *Amount `json:"vatAmount,omitempty"`
	// In v2 endpoints, monetary amounts are represented as objects with a `currency` and `value` field.
	GrossAmount *Amount `json:"grossAmount,omitempty"`
	// The collection of products which make up the invoice.
	Lines []EntityInvoiceLine `json:"lines,omitempty"`
	// The invoice date in `YYYY-MM-DD` format.
	IssuedAt *string `json:"issuedAt,omitempty"`
	// The date on which the invoice was paid, if applicable, in `YYYY-MM-DD` format.
	PaidAt *string `json:"paidAt,omitempty"`
	// The date on which the invoice is due, if applicable, in `YYYY-MM-DD` format.
	DueAt *string `json:"dueAt,omitempty"`
	// An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
	Links *EntityInvoiceLinks `json:"_links,omitempty"`
}

func (o *EntityInvoice) GetResource() *string {
	if o == nil {
		return nil
	}
	return o.Resource
}

func (o *EntityInvoice) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *EntityInvoice) GetReference() *string {
	if o == nil {
		return nil
	}
	return o.Reference
}

func (o *EntityInvoice) GetVatNumber() *string {
	if o == nil {
		return nil
	}
	return o.VatNumber
}

func (o *EntityInvoice) GetStatus() *EntityInvoiceStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *EntityInvoice) GetNetAmount() *Amount {
	if o == nil {
		return nil
	}
	return o.NetAmount
}

func (o *EntityInvoice) GetVatAmount() *Amount {
	if o == nil {
		return nil
	}
	return o.VatAmount
}

func (o *EntityInvoice) GetGrossAmount() *Amount {
	if o == nil {
		return nil
	}
	return o.GrossAmount
}

func (o *EntityInvoice) GetLines() []EntityInvoiceLine {
	if o == nil {
		return nil
	}
	return o.Lines
}

func (o *EntityInvoice) GetIssuedAt() *string {
	if o == nil {
		return nil
	}
	return o.IssuedAt
}

func (o *EntityInvoice) GetPaidAt() *string {
	if o == nil {
		return nil
	}
	return o.PaidAt
}

func (o *EntityInvoice) GetDueAt() *string {
	if o == nil {
		return nil
	}
	return o.DueAt
}

func (o *EntityInvoice) GetLinks() *EntityInvoiceLinks {
	if o == nil {
		return nil
	}
	return o.Links
}
