// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 5eccbd7d061a

package components

// EntityPairingCodeStatus - The status of the pairing code.
type EntityPairingCodeStatus string

const (
	EntityPairingCodeStatusActive  EntityPairingCodeStatus = "active"
	EntityPairingCodeStatusExpired EntityPairingCodeStatus = "expired"
	EntityPairingCodeStatusRevoked EntityPairingCodeStatus = "revoked"
)

func (e EntityPairingCodeStatus) ToPointer() *EntityPairingCodeStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *EntityPairingCodeStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "active", "expired", "revoked":
			return true
		}
	}
	return false
}

// EntityPairingCodeQrCode - The QR code representation of the pairing code.
type EntityPairingCodeQrCode struct {
	Height *float64 `json:"height,omitempty"`
	Width  *float64 `json:"width,omitempty"`
	Src    *string  `json:"src,omitempty"`
}

func (e *EntityPairingCodeQrCode) GetHeight() *float64 {
	if e == nil {
		return nil
	}
	return e.Height
}

func (e *EntityPairingCodeQrCode) GetWidth() *float64 {
	if e == nil {
		return nil
	}
	return e.Width
}

func (e *EntityPairingCodeQrCode) GetSrc() *string {
	if e == nil {
		return nil
	}
	return e.Src
}

// EntityPairingCodeDetails - Additional pairing code data, present only when requested via the `include` parameter.
type EntityPairingCodeDetails struct {
	// The QR code representation of the pairing code.
	QrCode *EntityPairingCodeQrCode `json:"qrCode,omitempty"`
}

func (e *EntityPairingCodeDetails) GetQrCode() *EntityPairingCodeQrCode {
	if e == nil {
		return nil
	}
	return e.QrCode
}

// EntityPairingCodeLinks - An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
type EntityPairingCodeLinks struct {
	// In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
	Self URLObj `json:"self"`
	// In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
	Profile URLObj `json:"profile"`
	// In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
	Documentation URLObj `json:"documentation"`
}

func (e *EntityPairingCodeLinks) GetSelf() URLObj {
	if e == nil {
		return URLObj{}
	}
	return e.Self
}

func (e *EntityPairingCodeLinks) GetProfile() URLObj {
	if e == nil {
		return URLObj{}
	}
	return e.Profile
}

func (e *EntityPairingCodeLinks) GetDocumentation() URLObj {
	if e == nil {
		return URLObj{}
	}
	return e.Documentation
}

type EntityPairingCode struct {
	// Indicates the response contains a terminal pairing code object. Will always contain the string
	// `terminal-pairing-code` for this endpoint.
	Resource string `json:"resource"`
	// The unique identifier of the pairing code. Example: `termpc_R7gX5Ea9bC4DkFj3G`.
	ID string `json:"id"`
	// Whether this entity was created in live mode or in test mode.
	Mode Mode `json:"mode"`
	// The human-readable pairing code to be entered on the terminal. This code is multi-use and will expire after the
	// time indicated in `expiresAt`.
	Code string `json:"code"`
	// The ID of the profile the terminal is being paired with.
	ProfileID string                  `json:"profileId"`
	Status    EntityPairingCodeStatus `json:"status"`
	// Additional pairing code data, present only when requested via the `include` parameter.
	Details *EntityPairingCodeDetails `json:"details,omitempty"`
	// The date and time the pairing code expires, in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format. Pairing
	// codes expire 90 days after creation. After this time, the code can no longer be used to pair a terminal.
	ExpiresAt string `json:"expiresAt"`
	// The date and time the pairing code was revoked, in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
	// `null` if the code has not been revoked.
	RevokedAt *string `json:"revokedAt,omitempty"`
	// The entity's date and time of creation, in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
	CreatedAt string `json:"createdAt"`
	// An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
	Links EntityPairingCodeLinks `json:"_links"`
}

func (e *EntityPairingCode) GetResource() string {
	if e == nil {
		return ""
	}
	return e.Resource
}

func (e *EntityPairingCode) GetID() string {
	if e == nil {
		return ""
	}
	return e.ID
}

func (e *EntityPairingCode) GetMode() Mode {
	if e == nil {
		return Mode("")
	}
	return e.Mode
}

func (e *EntityPairingCode) GetCode() string {
	if e == nil {
		return ""
	}
	return e.Code
}

func (e *EntityPairingCode) GetProfileID() string {
	if e == nil {
		return ""
	}
	return e.ProfileID
}

func (e *EntityPairingCode) GetStatus() EntityPairingCodeStatus {
	if e == nil {
		return EntityPairingCodeStatus("")
	}
	return e.Status
}

func (e *EntityPairingCode) GetDetails() *EntityPairingCodeDetails {
	if e == nil {
		return nil
	}
	return e.Details
}

func (e *EntityPairingCode) GetExpiresAt() string {
	if e == nil {
		return ""
	}
	return e.ExpiresAt
}

func (e *EntityPairingCode) GetRevokedAt() *string {
	if e == nil {
		return nil
	}
	return e.RevokedAt
}

func (e *EntityPairingCode) GetCreatedAt() string {
	if e == nil {
		return ""
	}
	return e.CreatedAt
}

func (e *EntityPairingCode) GetLinks() EntityPairingCodeLinks {
	if e == nil {
		return EntityPairingCodeLinks{}
	}
	return e.Links
}
