// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// EntityCapabilityRequirementStatus - The status of the requirement depends on its due date.
// If no due date is given, the status will be `requested`.
type EntityCapabilityRequirementStatus string

const (
	EntityCapabilityRequirementStatusCurrentlyDue EntityCapabilityRequirementStatus = "currently-due"
	EntityCapabilityRequirementStatusPastDue      EntityCapabilityRequirementStatus = "past-due"
	EntityCapabilityRequirementStatusRequested    EntityCapabilityRequirementStatus = "requested"
)

func (e EntityCapabilityRequirementStatus) ToPointer() *EntityCapabilityRequirementStatus {
	return &e
}
func (e *EntityCapabilityRequirementStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "currently-due":
		fallthrough
	case "past-due":
		fallthrough
	case "requested":
		*e = EntityCapabilityRequirementStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EntityCapabilityRequirementStatus: %v", v)
	}
}

// Dashboard - If known, a deep link to the Mollie dashboard of the client, where the requirement can be fulfilled.
// For example, where necessary documents are to be uploaded.
type Dashboard struct {
	// The actual URL string.
	Href *string `json:"href,omitempty"`
	// The content type of the page or endpoint the URL points to.
	Type *string `json:"type,omitempty"`
}

func (o *Dashboard) GetHref() *string {
	if o == nil {
		return nil
	}
	return o.Href
}

func (o *Dashboard) GetType() *string {
	if o == nil {
		return nil
	}
	return o.Type
}

type EntityCapabilityRequirementLinks struct {
	// If known, a deep link to the Mollie dashboard of the client, where the requirement can be fulfilled.
	// For example, where necessary documents are to be uploaded.
	Dashboard *Dashboard `json:"dashboard,omitempty"`
}

func (o *EntityCapabilityRequirementLinks) GetDashboard() *Dashboard {
	if o == nil {
		return nil
	}
	return o.Dashboard
}

type EntityCapabilityRequirement struct {
	// The name of this requirement, referring to the task to be fulfilled by the organization
	// to enable or re-enable the capability. The name is unique among other requirements
	// of the same capability.
	ID *string `json:"id,omitempty"`
	// The status of the requirement depends on its due date.
	// If no due date is given, the status will be `requested`.
	Status *EntityCapabilityRequirementStatus `json:"status,omitempty"`
	// Due date until the requirement must be fulfilled, if any. The date is shown in ISO-8601 format.
	DueDate *string                           `json:"dueDate,omitempty"`
	Links   *EntityCapabilityRequirementLinks `json:"_links,omitempty"`
}

func (o *EntityCapabilityRequirement) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *EntityCapabilityRequirement) GetStatus() *EntityCapabilityRequirementStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *EntityCapabilityRequirement) GetDueDate() *string {
	if o == nil {
		return nil
	}
	return o.DueDate
}

func (o *EntityCapabilityRequirement) GetLinks() *EntityCapabilityRequirementLinks {
	if o == nil {
		return nil
	}
	return o.Links
}
