// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 1b64c482dbfe

package components

// EntityOrganizationLocale - The preferred locale of the merchant, as set in their Mollie dashboard.
type EntityOrganizationLocale string

const (
	EntityOrganizationLocaleCaEs EntityOrganizationLocale = "ca_ES"
	EntityOrganizationLocaleCsCz EntityOrganizationLocale = "cs_CZ"
	EntityOrganizationLocaleDaDk EntityOrganizationLocale = "da_DK"
	EntityOrganizationLocaleDeAt EntityOrganizationLocale = "de_AT"
	EntityOrganizationLocaleDeCh EntityOrganizationLocale = "de_CH"
	EntityOrganizationLocaleDeDe EntityOrganizationLocale = "de_DE"
	EntityOrganizationLocaleDeLu EntityOrganizationLocale = "de_LU"
	EntityOrganizationLocaleEnGb EntityOrganizationLocale = "en_GB"
	EntityOrganizationLocaleEnUs EntityOrganizationLocale = "en_US"
	EntityOrganizationLocaleEsEs EntityOrganizationLocale = "es_ES"
	EntityOrganizationLocaleFiFi EntityOrganizationLocale = "fi_FI"
	EntityOrganizationLocaleFrBe EntityOrganizationLocale = "fr_BE"
	EntityOrganizationLocaleFrFr EntityOrganizationLocale = "fr_FR"
	EntityOrganizationLocaleFrLu EntityOrganizationLocale = "fr_LU"
	EntityOrganizationLocaleHuHu EntityOrganizationLocale = "hu_HU"
	EntityOrganizationLocaleIsIs EntityOrganizationLocale = "is_IS"
	EntityOrganizationLocaleItIt EntityOrganizationLocale = "it_IT"
	EntityOrganizationLocaleLtLt EntityOrganizationLocale = "lt_LT"
	EntityOrganizationLocaleLvLv EntityOrganizationLocale = "lv_LV"
	EntityOrganizationLocaleNbNo EntityOrganizationLocale = "nb_NO"
	EntityOrganizationLocaleNlBe EntityOrganizationLocale = "nl_BE"
	EntityOrganizationLocaleNlNl EntityOrganizationLocale = "nl_NL"
	EntityOrganizationLocalePlPl EntityOrganizationLocale = "pl_PL"
	EntityOrganizationLocalePtPt EntityOrganizationLocale = "pt_PT"
	EntityOrganizationLocaleSkSk EntityOrganizationLocale = "sk_SK"
	EntityOrganizationLocaleSvSe EntityOrganizationLocale = "sv_SE"
	EntityOrganizationLocaleNull EntityOrganizationLocale = "null"
)

func (e EntityOrganizationLocale) ToPointer() *EntityOrganizationLocale {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *EntityOrganizationLocale) IsExact() bool {
	if e != nil {
		switch *e {
		case "ca_ES", "cs_CZ", "da_DK", "de_AT", "de_CH", "de_DE", "de_LU", "en_GB", "en_US", "es_ES", "fi_FI", "fr_BE", "fr_FR", "fr_LU", "hu_HU", "is_IS", "it_IT", "lt_LT", "lv_LV", "nb_NO", "nl_BE", "nl_NL", "pl_PL", "pt_PT", "sk_SK", "sv_SE", "null":
			return true
		}
	}
	return false
}

// EntityOrganizationLinks - An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
type EntityOrganizationLinks struct {
	// In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
	Self *URLObj `json:"self,omitempty"`
	// In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
	Dashboard *URLObj `json:"dashboard,omitempty"`
	// In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
	Documentation *URLObj `json:"documentation,omitempty"`
}

func (e *EntityOrganizationLinks) GetSelf() *URLObj {
	if e == nil {
		return nil
	}
	return e.Self
}

func (e *EntityOrganizationLinks) GetDashboard() *URLObj {
	if e == nil {
		return nil
	}
	return e.Dashboard
}

func (e *EntityOrganizationLinks) GetDocumentation() *URLObj {
	if e == nil {
		return nil
	}
	return e.Documentation
}

type EntityOrganization struct {
	// Indicates the response contains an organization object. Will always contain the string `organization` for this
	// resource type.
	Resource string `json:"resource"`
	ID       string `json:"id"`
	// The name of the organization.
	Name string `json:"name"`
	// The email address associated with the organization.
	//
	// If the domain contains non-ASCII characters, encode it as Punycode per [RFC 3492](https://www.rfc-editor.org/rfc/rfc3492).
	Email string `json:"email"`
	// The preferred locale of the merchant, as set in their Mollie dashboard.
	Locale  *EntityOrganizationLocale `json:"locale"`
	Address *Address                  `json:"address,omitempty"`
	// The registration number of the organization at their local chamber of commerce.
	RegistrationNumber *string `json:"registrationNumber,omitempty"`
	// The VAT number of the organization, if based in the European Union or in The United Kingdom. VAT numbers are
	// verified against the international registry *VIES*.
	//
	// The field is not present for merchants residing in other countries.
	VatNumber *string `json:"vatNumber,omitempty"`
	// Mollie applies Dutch VAT for merchants based in The Netherlands, British VAT for merchants based in The United
	// Kingdom, and shifted VAT for merchants in the European Union.
	//
	// The field is not present for merchants residing in other countries.
	VatRegulation *OrganizationVatRegulation `json:"vatRegulation,omitempty"`
	// An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
	Links EntityOrganizationLinks `json:"_links"`
}

func (e *EntityOrganization) GetResource() string {
	if e == nil {
		return ""
	}
	return e.Resource
}

func (e *EntityOrganization) GetID() string {
	if e == nil {
		return ""
	}
	return e.ID
}

func (e *EntityOrganization) GetName() string {
	if e == nil {
		return ""
	}
	return e.Name
}

func (e *EntityOrganization) GetEmail() string {
	if e == nil {
		return ""
	}
	return e.Email
}

func (e *EntityOrganization) GetLocale() *EntityOrganizationLocale {
	if e == nil {
		return nil
	}
	return e.Locale
}

func (e *EntityOrganization) GetAddress() *Address {
	if e == nil {
		return nil
	}
	return e.Address
}

func (e *EntityOrganization) GetRegistrationNumber() *string {
	if e == nil {
		return nil
	}
	return e.RegistrationNumber
}

func (e *EntityOrganization) GetVatNumber() *string {
	if e == nil {
		return nil
	}
	return e.VatNumber
}

func (e *EntityOrganization) GetVatRegulation() *OrganizationVatRegulation {
	if e == nil {
		return nil
	}
	return e.VatRegulation
}

func (e *EntityOrganization) GetLinks() EntityOrganizationLinks {
	if e == nil {
		return EntityOrganizationLinks{}
	}
	return e.Links
}
