// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// EntityMethodImage - URLs of images representing the payment method.
type EntityMethodImage struct {
	// The URL pointing to an icon of 32 by 24 pixels.
	Size1x string `json:"size1x"`
	// The URL pointing to an icon of 64 by 48 pixels.
	Size2x string `json:"size2x"`
	// The URL pointing to a vector version of the icon. Usage of this format is preferred, since the icon can
	// scale to any desired size without compromising visual quality.
	Svg string `json:"svg"`
}

func (o *EntityMethodImage) GetSize1x() string {
	if o == nil {
		return ""
	}
	return o.Size1x
}

func (o *EntityMethodImage) GetSize2x() string {
	if o == nil {
		return ""
	}
	return o.Size2x
}

func (o *EntityMethodImage) GetSvg() string {
	if o == nil {
		return ""
	}
	return o.Svg
}

// EntityMethodIssuerImage - URLs of images representing the issuer.
// required:
//   - size1x
//   - size2x
//   - svg
type EntityMethodIssuerImage struct {
	// The URL pointing to an icon of 32 by 24 pixels.
	Size1x *string `json:"size1x,omitempty"`
	// The URL pointing to an icon of 64 by 48 pixels.
	Size2x *string `json:"size2x,omitempty"`
	// The URL pointing to a vector version of the icon. Usage of this format is preferred, since the icon can
	// scale to any desired size without compromising visual quality.
	Svg *string `json:"svg,omitempty"`
}

func (o *EntityMethodIssuerImage) GetSize1x() *string {
	if o == nil {
		return nil
	}
	return o.Size1x
}

func (o *EntityMethodIssuerImage) GetSize2x() *string {
	if o == nil {
		return nil
	}
	return o.Size2x
}

func (o *EntityMethodIssuerImage) GetSvg() *string {
	if o == nil {
		return nil
	}
	return o.Svg
}

type EntityMethodIssuer struct {
	Resource string `json:"resource"`
	ID       string `json:"id"`
	// The full name of the issuer.
	Name string `json:"name"`
	// URLs of images representing the issuer.
	// required:
	//   - size1x
	//   - size2x
	//   - svg
	Image EntityMethodIssuerImage `json:"image"`
}

func (o *EntityMethodIssuer) GetResource() string {
	if o == nil {
		return ""
	}
	return o.Resource
}

func (o *EntityMethodIssuer) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *EntityMethodIssuer) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *EntityMethodIssuer) GetImage() EntityMethodIssuerImage {
	if o == nil {
		return EntityMethodIssuerImage{}
	}
	return o.Image
}

// EntityMethodLinks - An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
type EntityMethodLinks struct {
	// In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
	Self URLObj `json:"self"`
	// In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
	Documentation *URLObj `json:"documentation,omitempty"`
}

func (o *EntityMethodLinks) GetSelf() URLObj {
	if o == nil {
		return URLObj{}
	}
	return o.Self
}

func (o *EntityMethodLinks) GetDocumentation() *URLObj {
	if o == nil {
		return nil
	}
	return o.Documentation
}

type EntityMethod struct {
	// Indicates the response contains a payment method object. Will always contain the string `method` for this
	// endpoint.
	Resource string `json:"resource"`
	// Normally, a payment method screen is shown. However, when using this parameter, you can choose a specific payment
	// method and your customer will skip the selection screen and is sent directly to the chosen payment method. The
	// parameter enables you to fully integrate the payment method selection into your website.
	//
	// You can also specify the methods in an array. By doing so we will still show the payment method selection screen
	// but will only show the methods specified in the array. For example, you can use this functionality to only show
	// payment methods from a specific country to your customer `['bancontact', 'belfius']`.
	ID *MethodResponse `json:"id"`
	// The full name of the payment method.
	//
	// If a `locale` parameter is provided, the name is translated to the given locale if possible.
	Description string `json:"description"`
	// In v2 endpoints, monetary amounts are represented as objects with a `currency` and `value` field.
	MinimumAmount Amount `json:"minimumAmount"`
	// In v2 endpoints, monetary amounts are represented as objects with a `currency` and `value` field.
	MaximumAmount *AmountNullable `json:"maximumAmount"`
	// URLs of images representing the payment method.
	Image EntityMethodImage `json:"image"`
	// The payment method's activation status for this profile.
	Status MethodStatus `json:"status"`
	// **Optional include.** Array of objects for each 'issuer' that is available for this payment method. Only relevant
	// for iDEAL, KBC/CBC, gift cards, and vouchers.
	Issuers []EntityMethodIssuer `json:"issuers,omitempty"`
	// An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
	Links EntityMethodLinks `json:"_links"`
}

func (o *EntityMethod) GetResource() string {
	if o == nil {
		return ""
	}
	return o.Resource
}

func (o *EntityMethod) GetID() *MethodResponse {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *EntityMethod) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

func (o *EntityMethod) GetMinimumAmount() Amount {
	if o == nil {
		return Amount{}
	}
	return o.MinimumAmount
}

func (o *EntityMethod) GetMaximumAmount() *AmountNullable {
	if o == nil {
		return nil
	}
	return o.MaximumAmount
}

func (o *EntityMethod) GetImage() EntityMethodImage {
	if o == nil {
		return EntityMethodImage{}
	}
	return o.Image
}

func (o *EntityMethod) GetStatus() MethodStatus {
	if o == nil {
		return MethodStatus("")
	}
	return o.Status
}

func (o *EntityMethod) GetIssuers() []EntityMethodIssuer {
	if o == nil {
		return nil
	}
	return o.Issuers
}

func (o *EntityMethod) GetLinks() EntityMethodLinks {
	if o == nil {
		return EntityMethodLinks{}
	}
	return o.Links
}
