// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: e9ccb1b2b04d

package components

import (
	"github.com/mollie/mollie-api-golang/internal/utils"
)

// GiftcardStatus - The status of the issuer.
// If the status is `pending-issuer`, an additional action from your side may be required with the issuer.
type GiftcardStatus string

const (
	GiftcardStatusActivated     GiftcardStatus = "activated"
	GiftcardStatusPendingIssuer GiftcardStatus = "pending-issuer"
)

func (e GiftcardStatus) ToPointer() *GiftcardStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *GiftcardStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "activated", "pending-issuer":
			return true
		}
	}
	return false
}

// GiftcardLinks - An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
type GiftcardLinks struct {
	// In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
	Self *URLObj `json:"self,omitempty"`
	// In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
	Documentation *URLObj `json:"documentation,omitempty"`
}

func (g GiftcardLinks) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GiftcardLinks) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GiftcardLinks) GetSelf() *URLObj {
	if g == nil {
		return nil
	}
	return g.Self
}

func (g *GiftcardLinks) GetDocumentation() *URLObj {
	if g == nil {
		return nil
	}
	return g.Documentation
}

type Giftcard struct {
	// Indicates the response contains a payment method issuer object. Will always contain the string `issuer` for this
	// endpoint.
	Resource string `json:"resource"`
	// The unique identifier of the payment method issuer.
	ID string `json:"id"`
	// The full name of the payment method issuer.
	Description string         `json:"description"`
	Status      GiftcardStatus `json:"status"`
	// An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
	Links GiftcardLinks `json:"_links"`
}

func (g Giftcard) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *Giftcard) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"resource", "id", "description", "status", "_links"}); err != nil {
		return err
	}
	return nil
}

func (g *Giftcard) GetResource() string {
	if g == nil {
		return ""
	}
	return g.Resource
}

func (g *Giftcard) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *Giftcard) GetDescription() string {
	if g == nil {
		return ""
	}
	return g.Description
}

func (g *Giftcard) GetStatus() GiftcardStatus {
	if g == nil {
		return GiftcardStatus("")
	}
	return g.Status
}

func (g *Giftcard) GetLinks() GiftcardLinks {
	if g == nil {
		return GiftcardLinks{}
	}
	return g.Links
}
