// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LineCategoriesResponse string

const (
	LineCategoriesResponseEco          LineCategoriesResponse = "eco"
	LineCategoriesResponseGift         LineCategoriesResponse = "gift"
	LineCategoriesResponseMeal         LineCategoriesResponse = "meal"
	LineCategoriesResponseSportCulture LineCategoriesResponse = "sport_culture"
	LineCategoriesResponseAdditional   LineCategoriesResponse = "additional"
	LineCategoriesResponseConsume      LineCategoriesResponse = "consume"
)

func (e LineCategoriesResponse) ToPointer() *LineCategoriesResponse {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *LineCategoriesResponse) IsExact() bool {
	if e != nil {
		switch *e {
		case "eco", "gift", "meal", "sport_culture", "additional", "consume":
			return true
		}
	}
	return false
}
