// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ListLinks - Links to help navigate through the lists of items. Every URL object will contain an `href` and a `type` field.
type ListLinks struct {
	// In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
	Self URLObj `json:"self"`
	// In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
	Previous *URLNullable `json:"previous"`
	// In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
	Next *URLNullable `json:"next"`
	// In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
	Documentation URLObj `json:"documentation"`
}

func (l *ListLinks) GetSelf() URLObj {
	if l == nil {
		return URLObj{}
	}
	return l.Self
}

func (l *ListLinks) GetPrevious() *URLNullable {
	if l == nil {
		return nil
	}
	return l.Previous
}

func (l *ListLinks) GetNext() *URLNullable {
	if l == nil {
		return nil
	}
	return l.Next
}

func (l *ListLinks) GetDocumentation() URLObj {
	if l == nil {
		return URLObj{}
	}
	return l.Documentation
}
