// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type ListSort string

const (
	ListSortAsc  ListSort = "asc"
	ListSortDesc ListSort = "desc"
)

func (e ListSort) ToPointer() *ListSort {
	return &e
}
func (e *ListSort) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "asc":
		fallthrough
	case "desc":
		*e = ListSort(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListSort: %v", v)
	}
}
