// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ListEntitySettlementStatus - The status of the settlement.
type ListEntitySettlementStatus string

const (
	ListEntitySettlementStatusOpen    ListEntitySettlementStatus = "open"
	ListEntitySettlementStatusPending ListEntitySettlementStatus = "pending"
	ListEntitySettlementStatusPaidout ListEntitySettlementStatus = "paidout"
	ListEntitySettlementStatusFailed  ListEntitySettlementStatus = "failed"
)

func (e ListEntitySettlementStatus) ToPointer() *ListEntitySettlementStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ListEntitySettlementStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "open", "pending", "paidout", "failed":
			return true
		}
	}
	return false
}

// ListEntitySettlementAmount - The total amount of the settlement.
type ListEntitySettlementAmount struct {
	// A three-character ISO 4217 currency code.
	Currency string `json:"currency"`
	// A string containing an exact monetary amount in the given currency.
	Value string `json:"value"`
}

func (l *ListEntitySettlementAmount) GetCurrency() string {
	if l == nil {
		return ""
	}
	return l.Currency
}

func (l *ListEntitySettlementAmount) GetValue() string {
	if l == nil {
		return ""
	}
	return l.Value
}

// ListEntitySettlementRate - The service rates, further divided into `fixed` and `percentage` costs.
type ListEntitySettlementRate struct {
	// In v2 endpoints, monetary amounts are represented as objects with a `currency` and `value` field.
	Fixed      *Amount `json:"fixed,omitempty"`
	Percentage *string `json:"percentage,omitempty"`
}

func (l *ListEntitySettlementRate) GetFixed() *Amount {
	if l == nil {
		return nil
	}
	return l.Fixed
}

func (l *ListEntitySettlementRate) GetPercentage() *string {
	if l == nil {
		return nil
	}
	return l.Percentage
}

type ListEntitySettlementCost struct {
	// A description of the cost subtotal
	Description string `json:"description"`
	// The payment method, if applicable
	Method *PaymentMethod `json:"method"`
	// The number of fees
	Count int64 `json:"count"`
	// The service rates, further divided into `fixed` and `percentage` costs.
	Rate ListEntitySettlementRate `json:"rate"`
	// In v2 endpoints, monetary amounts are represented as objects with a `currency` and `value` field.
	AmountNet Amount `json:"amountNet"`
	// In v2 endpoints, monetary amounts are represented as objects with a `currency` and `value` field.
	AmountVat *AmountNullable `json:"amountVat"`
	// In v2 endpoints, monetary amounts are represented as objects with a `currency` and `value` field.
	AmountGross Amount `json:"amountGross"`
}

func (l *ListEntitySettlementCost) GetDescription() string {
	if l == nil {
		return ""
	}
	return l.Description
}

func (l *ListEntitySettlementCost) GetMethod() *PaymentMethod {
	if l == nil {
		return nil
	}
	return l.Method
}

func (l *ListEntitySettlementCost) GetCount() int64 {
	if l == nil {
		return 0
	}
	return l.Count
}

func (l *ListEntitySettlementCost) GetRate() ListEntitySettlementRate {
	if l == nil {
		return ListEntitySettlementRate{}
	}
	return l.Rate
}

func (l *ListEntitySettlementCost) GetAmountNet() Amount {
	if l == nil {
		return Amount{}
	}
	return l.AmountNet
}

func (l *ListEntitySettlementCost) GetAmountVat() *AmountNullable {
	if l == nil {
		return nil
	}
	return l.AmountVat
}

func (l *ListEntitySettlementCost) GetAmountGross() Amount {
	if l == nil {
		return Amount{}
	}
	return l.AmountGross
}

type ListEntitySettlementRevenue struct {
	// A description of the revenue subtotal
	Description string `json:"description"`
	// The payment method, if applicable
	Method *PaymentMethod `json:"method"`
	// The number of payments
	Count int64 `json:"count"`
	// In v2 endpoints, monetary amounts are represented as objects with a `currency` and `value` field.
	AmountNet Amount `json:"amountNet"`
	// In v2 endpoints, monetary amounts are represented as objects with a `currency` and `value` field.
	AmountVat *AmountNullable `json:"amountVat"`
	// In v2 endpoints, monetary amounts are represented as objects with a `currency` and `value` field.
	AmountGross Amount `json:"amountGross"`
}

func (l *ListEntitySettlementRevenue) GetDescription() string {
	if l == nil {
		return ""
	}
	return l.Description
}

func (l *ListEntitySettlementRevenue) GetMethod() *PaymentMethod {
	if l == nil {
		return nil
	}
	return l.Method
}

func (l *ListEntitySettlementRevenue) GetCount() int64 {
	if l == nil {
		return 0
	}
	return l.Count
}

func (l *ListEntitySettlementRevenue) GetAmountNet() Amount {
	if l == nil {
		return Amount{}
	}
	return l.AmountNet
}

func (l *ListEntitySettlementRevenue) GetAmountVat() *AmountNullable {
	if l == nil {
		return nil
	}
	return l.AmountVat
}

func (l *ListEntitySettlementRevenue) GetAmountGross() Amount {
	if l == nil {
		return Amount{}
	}
	return l.AmountGross
}

type ListEntitySettlementPeriods struct {
	// An array of cost objects, describing the fees withheld for each payment method during this period.
	Costs []ListEntitySettlementCost `json:"costs,omitempty"`
	// An array of revenue objects containing the total revenue for each payment method during this period.
	Revenue   []ListEntitySettlementRevenue `json:"revenue,omitempty"`
	InvoiceID *string                       `json:"invoiceId,omitempty"`
	// The invoice reference, if the invoice has been created already.
	InvoiceReference *string `json:"invoiceReference,omitempty"`
}

func (l *ListEntitySettlementPeriods) GetCosts() []ListEntitySettlementCost {
	if l == nil {
		return nil
	}
	return l.Costs
}

func (l *ListEntitySettlementPeriods) GetRevenue() []ListEntitySettlementRevenue {
	if l == nil {
		return nil
	}
	return l.Revenue
}

func (l *ListEntitySettlementPeriods) GetInvoiceID() *string {
	if l == nil {
		return nil
	}
	return l.InvoiceID
}

func (l *ListEntitySettlementPeriods) GetInvoiceReference() *string {
	if l == nil {
		return nil
	}
	return l.InvoiceReference
}

// ListEntitySettlementLinks - An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
type ListEntitySettlementLinks struct {
	// In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
	Self URLObj `json:"self"`
	// In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
	Payments *URLObj `json:"payments,omitempty"`
	// In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
	Captures *URLObj `json:"captures,omitempty"`
	// In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
	Refunds *URLObj `json:"refunds,omitempty"`
	// In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
	Chargebacks *URLObj `json:"chargebacks,omitempty"`
	// In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
	Invoice *URLNullable `json:"invoice,omitempty"`
}

func (l *ListEntitySettlementLinks) GetSelf() URLObj {
	if l == nil {
		return URLObj{}
	}
	return l.Self
}

func (l *ListEntitySettlementLinks) GetPayments() *URLObj {
	if l == nil {
		return nil
	}
	return l.Payments
}

func (l *ListEntitySettlementLinks) GetCaptures() *URLObj {
	if l == nil {
		return nil
	}
	return l.Captures
}

func (l *ListEntitySettlementLinks) GetRefunds() *URLObj {
	if l == nil {
		return nil
	}
	return l.Refunds
}

func (l *ListEntitySettlementLinks) GetChargebacks() *URLObj {
	if l == nil {
		return nil
	}
	return l.Chargebacks
}

func (l *ListEntitySettlementLinks) GetInvoice() *URLNullable {
	if l == nil {
		return nil
	}
	return l.Invoice
}

type ListEntitySettlement struct {
	// Indicates the response contains a settlement object. Will always contain the string `settlement` for this
	// endpoint.
	Resource string `json:"resource"`
	// The identifier uniquely referring to this settlement.
	ID string `json:"id"`
	// The entity's date and time of creation, in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
	CreatedAt *string `json:"createdAt,omitempty"`
	// The settlement's bank reference, as found in your Mollie account and on your bank statement.
	Reference *string `json:"reference,omitempty"`
	// The date on which the settlement was settled, in ISO 8601 format.
	//
	// For an [open settlement](get-open-settlement) or for the [next settlement](get-next-settlement), no settlement
	// date is available.
	SettledAt *string                    `json:"settledAt,omitempty"`
	Status    ListEntitySettlementStatus `json:"status"`
	// The total amount of the settlement.
	Amount ListEntitySettlementAmount `json:"amount"`
	// The balance token that the settlement was settled to.
	BalanceID string `json:"balanceId"`
	// The ID of the oldest invoice created for all the periods, if the invoice has been created yet.
	InvoiceID *string `json:"invoiceId,omitempty"`
	// For bookkeeping purposes, the settlement includes an overview of transactions included in the settlement. These
	// transactions are grouped into 'period' objects — one for each calendar month.
	//
	// For example, if a settlement includes funds from 15 April until 4 May, it will include two period objects. One for
	// all transactions processed between 15 April and 30 April, and one for all transactions between 1 May and 4 May.
	//
	// Period objects are grouped by year, and then by month. So in the above example, the full `periods` collection will
	// look as follows: `{"2024": {"04": {...}, "05": {...}}}`. The year and month in this documentation are referred as `<year>` and `<month>`.
	//
	// The example response should give a good idea of what this looks like in practise.
	Periods map[string]map[string]ListEntitySettlementPeriods `json:"periods,omitempty"`
	// An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
	Links ListEntitySettlementLinks `json:"_links"`
}

func (l *ListEntitySettlement) GetResource() string {
	if l == nil {
		return ""
	}
	return l.Resource
}

func (l *ListEntitySettlement) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *ListEntitySettlement) GetCreatedAt() *string {
	if l == nil {
		return nil
	}
	return l.CreatedAt
}

func (l *ListEntitySettlement) GetReference() *string {
	if l == nil {
		return nil
	}
	return l.Reference
}

func (l *ListEntitySettlement) GetSettledAt() *string {
	if l == nil {
		return nil
	}
	return l.SettledAt
}

func (l *ListEntitySettlement) GetStatus() ListEntitySettlementStatus {
	if l == nil {
		return ListEntitySettlementStatus("")
	}
	return l.Status
}

func (l *ListEntitySettlement) GetAmount() ListEntitySettlementAmount {
	if l == nil {
		return ListEntitySettlementAmount{}
	}
	return l.Amount
}

func (l *ListEntitySettlement) GetBalanceID() string {
	if l == nil {
		return ""
	}
	return l.BalanceID
}

func (l *ListEntitySettlement) GetInvoiceID() *string {
	if l == nil {
		return nil
	}
	return l.InvoiceID
}

func (l *ListEntitySettlement) GetPeriods() map[string]map[string]ListEntitySettlementPeriods {
	if l == nil {
		return nil
	}
	return l.Periods
}

func (l *ListEntitySettlement) GetLinks() ListEntitySettlementLinks {
	if l == nil {
		return ListEntitySettlementLinks{}
	}
	return l.Links
}
