// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 93b814fef79b

package components

import (
	"encoding/json"
	"fmt"
)

// Locale - Sets the language for customer-facing content and communications.
type Locale string

const (
	LocaleCaEs Locale = "ca_ES"
	LocaleCsCz Locale = "cs_CZ"
	LocaleDaDk Locale = "da_DK"
	LocaleDeAt Locale = "de_AT"
	LocaleDeCh Locale = "de_CH"
	LocaleDeDe Locale = "de_DE"
	LocaleDeLu Locale = "de_LU"
	LocaleEnGb Locale = "en_GB"
	LocaleEnUs Locale = "en_US"
	LocaleEsEs Locale = "es_ES"
	LocaleFiFi Locale = "fi_FI"
	LocaleFrBe Locale = "fr_BE"
	LocaleFrFr Locale = "fr_FR"
	LocaleFrLu Locale = "fr_LU"
	LocaleHuHu Locale = "hu_HU"
	LocaleIsIs Locale = "is_IS"
	LocaleItIt Locale = "it_IT"
	LocaleLtLt Locale = "lt_LT"
	LocaleLvLv Locale = "lv_LV"
	LocaleNbNo Locale = "nb_NO"
	LocaleNlBe Locale = "nl_BE"
	LocaleNlNl Locale = "nl_NL"
	LocalePlPl Locale = "pl_PL"
	LocalePtPt Locale = "pt_PT"
	LocaleSkSk Locale = "sk_SK"
	LocaleSvSe Locale = "sv_SE"
	LocaleNull Locale = "null"
)

func (e Locale) ToPointer() *Locale {
	return &e
}
func (e *Locale) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ca_ES":
		fallthrough
	case "cs_CZ":
		fallthrough
	case "da_DK":
		fallthrough
	case "de_AT":
		fallthrough
	case "de_CH":
		fallthrough
	case "de_DE":
		fallthrough
	case "de_LU":
		fallthrough
	case "en_GB":
		fallthrough
	case "en_US":
		fallthrough
	case "es_ES":
		fallthrough
	case "fi_FI":
		fallthrough
	case "fr_BE":
		fallthrough
	case "fr_FR":
		fallthrough
	case "fr_LU":
		fallthrough
	case "hu_HU":
		fallthrough
	case "is_IS":
		fallthrough
	case "it_IT":
		fallthrough
	case "lt_LT":
		fallthrough
	case "lv_LV":
		fallthrough
	case "nb_NO":
		fallthrough
	case "nl_BE":
		fallthrough
	case "nl_NL":
		fallthrough
	case "pl_PL":
		fallthrough
	case "pt_PT":
		fallthrough
	case "sk_SK":
		fallthrough
	case "sv_SE":
		fallthrough
	case "null":
		*e = Locale(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Locale: %v", v)
	}
}
