// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// MandateDetailsCardLabelResponse - The card's label. Available for card mandates, if the card label could be detected.
type MandateDetailsCardLabelResponse string

const (
	MandateDetailsCardLabelResponseAmericanExpress MandateDetailsCardLabelResponse = "American Express"
	MandateDetailsCardLabelResponseCartaSi         MandateDetailsCardLabelResponse = "Carta Si"
	MandateDetailsCardLabelResponseCarteBleue      MandateDetailsCardLabelResponse = "Carte Bleue"
	MandateDetailsCardLabelResponseDankort         MandateDetailsCardLabelResponse = "Dankort"
	MandateDetailsCardLabelResponseDinersClub      MandateDetailsCardLabelResponse = "Diners Club"
	MandateDetailsCardLabelResponseDiscover        MandateDetailsCardLabelResponse = "Discover"
	MandateDetailsCardLabelResponseJcb             MandateDetailsCardLabelResponse = "JCB"
	MandateDetailsCardLabelResponseLaser           MandateDetailsCardLabelResponse = "Laser"
	MandateDetailsCardLabelResponseMaestro         MandateDetailsCardLabelResponse = "Maestro"
	MandateDetailsCardLabelResponseMastercard      MandateDetailsCardLabelResponse = "Mastercard"
	MandateDetailsCardLabelResponseUnionpay        MandateDetailsCardLabelResponse = "Unionpay"
	MandateDetailsCardLabelResponseVisa            MandateDetailsCardLabelResponse = "Visa"
)

func (e MandateDetailsCardLabelResponse) ToPointer() *MandateDetailsCardLabelResponse {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *MandateDetailsCardLabelResponse) IsExact() bool {
	if e != nil {
		switch *e {
		case "American Express", "Carta Si", "Carte Bleue", "Dankort", "Diners Club", "Discover", "JCB", "Laser", "Maestro", "Mastercard", "Unionpay", "Visa":
			return true
		}
	}
	return false
}
