// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// MandateMethod - Payment method of the mandate.
//
// SEPA Direct Debit and PayPal mandates can be created directly.
type MandateMethod string

const (
	MandateMethodCreditcard  MandateMethod = "creditcard"
	MandateMethodDirectdebit MandateMethod = "directdebit"
	MandateMethodPaypal      MandateMethod = "paypal"
)

func (e MandateMethod) ToPointer() *MandateMethod {
	return &e
}
func (e *MandateMethod) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "creditcard":
		fallthrough
	case "directdebit":
		fallthrough
	case "paypal":
		*e = MandateMethod(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MandateMethod: %v", v)
	}
}
