// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// Mode - Whether this entity was created in live mode or in test mode.
type Mode string

const (
	ModeLive Mode = "live"
	ModeTest Mode = "test"
)

func (e Mode) ToPointer() *Mode {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Mode) IsExact() bool {
	if e != nil {
		switch *e {
		case "live", "test":
			return true
		}
	}
	return false
}
