// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// OnboardingStatus - The current status of the organization's onboarding process.
type OnboardingStatus string

const (
	OnboardingStatusNeedsData OnboardingStatus = "needs-data"
	OnboardingStatusInReview  OnboardingStatus = "in-review"
	OnboardingStatusCompleted OnboardingStatus = "completed"
)

func (e OnboardingStatus) ToPointer() *OnboardingStatus {
	return &e
}
