// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// OnboardingVatRegulation - Mollie applies Dutch VAT for merchants based in The Netherlands, British VAT for merchants based in
// The United Kingdom, and shifted VAT for merchants in the European Union.
//
// The field can be omitted for merchants residing in other countries.
type OnboardingVatRegulation string

const (
	OnboardingVatRegulationDutch   OnboardingVatRegulation = "dutch"
	OnboardingVatRegulationBritish OnboardingVatRegulation = "british"
	OnboardingVatRegulationShifted OnboardingVatRegulation = "shifted"
)

func (e OnboardingVatRegulation) ToPointer() *OnboardingVatRegulation {
	return &e
}
func (e *OnboardingVatRegulation) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "dutch":
		fallthrough
	case "british":
		fallthrough
	case "shifted":
		*e = OnboardingVatRegulation(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OnboardingVatRegulation: %v", v)
	}
}
