// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// PaymentDetailsWalletResponse - The wallet used when creating the payment.
type PaymentDetailsWalletResponse string

const (
	PaymentDetailsWalletResponseApplepay PaymentDetailsWalletResponse = "applepay"
)

func (e PaymentDetailsWalletResponse) ToPointer() *PaymentDetailsWalletResponse {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PaymentDetailsWalletResponse) IsExact() bool {
	if e != nil {
		switch *e {
		case "applepay":
			return true
		}
	}
	return false
}
