// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// PaymentDetailsCardLabelResponse - The card's label, if known.
type PaymentDetailsCardLabelResponse string

const (
	PaymentDetailsCardLabelResponseAmericanExpress PaymentDetailsCardLabelResponse = "American Express"
	PaymentDetailsCardLabelResponseCartaSi         PaymentDetailsCardLabelResponse = "Carta Si"
	PaymentDetailsCardLabelResponseCarteBleue      PaymentDetailsCardLabelResponse = "Carte Bleue"
	PaymentDetailsCardLabelResponseDankort         PaymentDetailsCardLabelResponse = "Dankort"
	PaymentDetailsCardLabelResponseDinersClub      PaymentDetailsCardLabelResponse = "Diners Club"
	PaymentDetailsCardLabelResponseDiscover        PaymentDetailsCardLabelResponse = "Discover"
	PaymentDetailsCardLabelResponseJcb             PaymentDetailsCardLabelResponse = "JCB"
	PaymentDetailsCardLabelResponseLaser           PaymentDetailsCardLabelResponse = "Laser"
	PaymentDetailsCardLabelResponseMaestro         PaymentDetailsCardLabelResponse = "Maestro"
	PaymentDetailsCardLabelResponseMastercard      PaymentDetailsCardLabelResponse = "Mastercard"
	PaymentDetailsCardLabelResponseUnionpay        PaymentDetailsCardLabelResponse = "Unionpay"
	PaymentDetailsCardLabelResponseVisa            PaymentDetailsCardLabelResponse = "Visa"
	PaymentDetailsCardLabelResponseVpay            PaymentDetailsCardLabelResponse = "Vpay"
)

func (e PaymentDetailsCardLabelResponse) ToPointer() *PaymentDetailsCardLabelResponse {
	return &e
}
