// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RecurringLineItem struct {
	// A description of the recurring item. If not present, the main description of the item will be used.
	Description *string `json:"description,omitempty"`
	// Cadence unit of the recurring item. For example: `12 months`, `52 weeks` or `365 days`.
	//
	// Possible values: `... days`, `... weeks`, `... months`.
	Interval string `json:"interval"`
	// In v2 endpoints, monetary amounts are represented as objects with a `currency` and `value` field.
	Amount *Amount `json:"amount,omitempty"`
	// Total number of charges for the subscription to complete. Leave empty for ongoing subscription.
	Times *int64 `json:"times,omitempty"`
	// The start date of the subscription if it does not start right away (format `YYYY-MM-DD`)
	StartDate *string `json:"startDate,omitempty"`
}

func (o *RecurringLineItem) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *RecurringLineItem) GetInterval() string {
	if o == nil {
		return ""
	}
	return o.Interval
}

func (o *RecurringLineItem) GetAmount() *Amount {
	if o == nil {
		return nil
	}
	return o.Amount
}

func (o *RecurringLineItem) GetTimes() *int64 {
	if o == nil {
		return nil
	}
	return o.Times
}

func (o *RecurringLineItem) GetStartDate() *string {
	if o == nil {
		return nil
	}
	return o.StartDate
}
