// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// RouteCreateRequestType - The type of destination. Currently only the destination type `organization` is supported.
type RouteCreateRequestType string

const (
	RouteCreateRequestTypeOrganization RouteCreateRequestType = "organization"
)

func (e RouteCreateRequestType) ToPointer() *RouteCreateRequestType {
	return &e
}
func (e *RouteCreateRequestType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "organization":
		*e = RouteCreateRequestType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RouteCreateRequestType: %v", v)
	}
}

// RouteCreateRequestDestination - The destination of the route.
type RouteCreateRequestDestination struct {
	// The type of destination. Currently only the destination type `organization` is supported.
	Type           RouteCreateRequestType `json:"type"`
	OrganizationID string                 `json:"organizationId"`
}

func (o *RouteCreateRequestDestination) GetType() RouteCreateRequestType {
	if o == nil {
		return RouteCreateRequestType("")
	}
	return o.Type
}

func (o *RouteCreateRequestDestination) GetOrganizationID() string {
	if o == nil {
		return ""
	}
	return o.OrganizationID
}

type RouteCreateRequest struct {
	ID        *string `json:"id,omitempty"`
	PaymentID *string `json:"paymentId,omitempty"`
	// In v2 endpoints, monetary amounts are represented as objects with a `currency` and `value` field.
	Amount *Amount `json:"amount,omitempty"`
	// The description of the route. This description is shown in the reports.
	Description *string `json:"description,omitempty"`
	// The destination of the route.
	Destination *RouteCreateRequestDestination `json:"destination,omitempty"`
	// Whether to create the entity in test mode or live mode.
	//
	// Most API credentials are specifically created for either live mode or test mode, in which case this parameter can be
	// omitted. For organization-level credentials such as OAuth access tokens, you can enable test mode by setting
	// `testmode` to `true`.
	Testmode *bool `json:"testmode,omitempty"`
}

func (o *RouteCreateRequest) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *RouteCreateRequest) GetPaymentID() *string {
	if o == nil {
		return nil
	}
	return o.PaymentID
}

func (o *RouteCreateRequest) GetAmount() *Amount {
	if o == nil {
		return nil
	}
	return o.Amount
}

func (o *RouteCreateRequest) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *RouteCreateRequest) GetDestination() *RouteCreateRequestDestination {
	if o == nil {
		return nil
	}
	return o.Destination
}

func (o *RouteCreateRequest) GetTestmode() *bool {
	if o == nil {
		return nil
	}
	return o.Testmode
}
