// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// RouteCreateResponseDestination - The destination of the route.
type RouteCreateResponseDestination struct {
	// The type of destination. Currently only the destination type `organization` is supported.
	Type           RouteDestinationTypeResponse `json:"type"`
	OrganizationID string                       `json:"organizationId"`
}

func (r *RouteCreateResponseDestination) GetType() RouteDestinationTypeResponse {
	if r == nil {
		return RouteDestinationTypeResponse("")
	}
	return r.Type
}

func (r *RouteCreateResponseDestination) GetOrganizationID() string {
	if r == nil {
		return ""
	}
	return r.OrganizationID
}

// RouteCreateResponseLinks - An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
type RouteCreateResponseLinks struct {
	// In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
	Self URLObj `json:"self"`
	// In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
	Documentation URLObj `json:"documentation"`
}

func (r *RouteCreateResponseLinks) GetSelf() URLObj {
	if r == nil {
		return URLObj{}
	}
	return r.Self
}

func (r *RouteCreateResponseLinks) GetDocumentation() URLObj {
	if r == nil {
		return URLObj{}
	}
	return r.Documentation
}

type RouteCreateResponse struct {
	// Indicates the response contains a route object. Will always contain the string `route` for this endpoint.
	Resource string `json:"resource"`
	// The identifier uniquely referring to this route. Mollie assigns this identifier at route creation time. Mollie
	// will always refer to the route by this ID. Example: `crt_dyARQ3JzCgtPDhU2Pbq3J`.
	ID string `json:"id"`
	// The unique identifier of the payment. For example: `tr_5B8cwPMGnU6qLbRvo7qEZo`.
	// The full payment object can be retrieved via the payment URL in the `_links` object.
	PaymentID string `json:"paymentId"`
	// In v2 endpoints, monetary amounts are represented as objects with a `currency` and `value` field.
	Amount Amount `json:"amount"`
	// The description of the route. This description is shown in the reports.
	Description string `json:"description"`
	// The destination of the route.
	Destination RouteCreateResponseDestination `json:"destination"`
	// An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
	Links RouteCreateResponseLinks `json:"_links"`
}

func (r *RouteCreateResponse) GetResource() string {
	if r == nil {
		return ""
	}
	return r.Resource
}

func (r *RouteCreateResponse) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

func (r *RouteCreateResponse) GetPaymentID() string {
	if r == nil {
		return ""
	}
	return r.PaymentID
}

func (r *RouteCreateResponse) GetAmount() Amount {
	if r == nil {
		return Amount{}
	}
	return r.Amount
}

func (r *RouteCreateResponse) GetDescription() string {
	if r == nil {
		return ""
	}
	return r.Description
}

func (r *RouteCreateResponse) GetDestination() RouteCreateResponseDestination {
	if r == nil {
		return RouteCreateResponseDestination{}
	}
	return r.Destination
}

func (r *RouteCreateResponse) GetLinks() RouteCreateResponseLinks {
	if r == nil {
		return RouteCreateResponseLinks{}
	}
	return r.Links
}
