// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// SalesInvoiceVatModeResponse - The VAT mode to use for VAT calculation. `exclusive` mode means we will apply the relevant VAT on top of the
// price. `inclusive` means the prices you are providing to us already contain the VAT you want to apply.
type SalesInvoiceVatModeResponse string

const (
	SalesInvoiceVatModeResponseExclusive SalesInvoiceVatModeResponse = "exclusive"
	SalesInvoiceVatModeResponseInclusive SalesInvoiceVatModeResponse = "inclusive"
)

func (e SalesInvoiceVatModeResponse) ToPointer() *SalesInvoiceVatModeResponse {
	return &e
}
