// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// SalesInvoiceDiscountTypeResponse - The type of discount.
type SalesInvoiceDiscountTypeResponse string

const (
	SalesInvoiceDiscountTypeResponseAmount     SalesInvoiceDiscountTypeResponse = "amount"
	SalesInvoiceDiscountTypeResponsePercentage SalesInvoiceDiscountTypeResponse = "percentage"
)

func (e SalesInvoiceDiscountTypeResponse) ToPointer() *SalesInvoiceDiscountTypeResponse {
	return &e
}
