// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SalesInvoiceLineItem struct {
	// A description of the line item. For example *LEGO 4440 Forest Police Station*.
	Description string `json:"description"`
	// The number of items.
	Quantity int64 `json:"quantity"`
	// The vat rate to be applied to this line item.
	VatRate string `json:"vatRate"`
	// In v2 endpoints, monetary amounts are represented as objects with a `currency` and `value` field.
	UnitPrice Amount                `json:"unitPrice"`
	Discount  *SalesInvoiceDiscount `json:"discount,omitempty"`
}

func (o *SalesInvoiceLineItem) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

func (o *SalesInvoiceLineItem) GetQuantity() int64 {
	if o == nil {
		return 0
	}
	return o.Quantity
}

func (o *SalesInvoiceLineItem) GetVatRate() string {
	if o == nil {
		return ""
	}
	return o.VatRate
}

func (o *SalesInvoiceLineItem) GetUnitPrice() Amount {
	if o == nil {
		return Amount{}
	}
	return o.UnitPrice
}

func (o *SalesInvoiceLineItem) GetDiscount() *SalesInvoiceDiscount {
	if o == nil {
		return nil
	}
	return o.Discount
}
