// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SalesInvoiceLineItemResponse struct {
	// A description of the line item. For example *LEGO 4440 Forest Police Station*.
	Description string `json:"description"`
	// The number of items.
	Quantity int64 `json:"quantity"`
	// The vat rate to be applied to this line item.
	VatRate string `json:"vatRate"`
	// In v2 endpoints, monetary amounts are represented as objects with a `currency` and `value` field.
	UnitPrice Amount                        `json:"unitPrice"`
	Discount  *SalesInvoiceDiscountResponse `json:"discount,omitempty"`
}

func (s *SalesInvoiceLineItemResponse) GetDescription() string {
	if s == nil {
		return ""
	}
	return s.Description
}

func (s *SalesInvoiceLineItemResponse) GetQuantity() int64 {
	if s == nil {
		return 0
	}
	return s.Quantity
}

func (s *SalesInvoiceLineItemResponse) GetVatRate() string {
	if s == nil {
		return ""
	}
	return s.VatRate
}

func (s *SalesInvoiceLineItemResponse) GetUnitPrice() Amount {
	if s == nil {
		return Amount{}
	}
	return s.UnitPrice
}

func (s *SalesInvoiceLineItemResponse) GetDiscount() *SalesInvoiceDiscountResponse {
	if s == nil {
		return nil
	}
	return s.Discount
}
