// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SalesInvoicePaymentDetails struct {
	// The way through which the invoice is to be set to paid.
	Source SalesInvoicePaymentDetailsSource `json:"source"`
	// A reference to the payment the sales invoice is paid by. Required for `source` values `payment-link` and
	// `payment`.
	SourceReference *string `json:"sourceReference,omitempty"`
}

func (o *SalesInvoicePaymentDetails) GetSource() SalesInvoicePaymentDetailsSource {
	if o == nil {
		return SalesInvoicePaymentDetailsSource("")
	}
	return o.Source
}

func (o *SalesInvoicePaymentDetails) GetSourceReference() *string {
	if o == nil {
		return nil
	}
	return o.SourceReference
}
