// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 8ff0f34325c1

package components

import (
	"encoding/json"
	"fmt"
)

// SalesInvoiceRecipientLocale - The locale for the recipient, to be used for translations in PDF generation and payment pages.
type SalesInvoiceRecipientLocale string

const (
	SalesInvoiceRecipientLocaleEnUs SalesInvoiceRecipientLocale = "en_US"
	SalesInvoiceRecipientLocaleEnGb SalesInvoiceRecipientLocale = "en_GB"
	SalesInvoiceRecipientLocaleNlNl SalesInvoiceRecipientLocale = "nl_NL"
	SalesInvoiceRecipientLocaleNlBe SalesInvoiceRecipientLocale = "nl_BE"
	SalesInvoiceRecipientLocaleDeDe SalesInvoiceRecipientLocale = "de_DE"
	SalesInvoiceRecipientLocaleDeAt SalesInvoiceRecipientLocale = "de_AT"
	SalesInvoiceRecipientLocaleDeCh SalesInvoiceRecipientLocale = "de_CH"
	SalesInvoiceRecipientLocaleFrFr SalesInvoiceRecipientLocale = "fr_FR"
	SalesInvoiceRecipientLocaleFrBe SalesInvoiceRecipientLocale = "fr_BE"
)

func (e SalesInvoiceRecipientLocale) ToPointer() *SalesInvoiceRecipientLocale {
	return &e
}
func (e *SalesInvoiceRecipientLocale) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "en_US":
		fallthrough
	case "en_GB":
		fallthrough
	case "nl_NL":
		fallthrough
	case "nl_BE":
		fallthrough
	case "de_DE":
		fallthrough
	case "de_AT":
		fallthrough
	case "de_CH":
		fallthrough
	case "fr_FR":
		fallthrough
	case "fr_BE":
		*e = SalesInvoiceRecipientLocale(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SalesInvoiceRecipientLocale: %v", v)
	}
}

type SalesInvoiceRecipient struct {
	// The type of recipient, either `consumer` or `business`. This will determine what further fields are
	// required on the `recipient` object.
	Type SalesInvoiceRecipientType `json:"type"`
	// The title of the `consumer` type recipient, for example Mr. or Mrs..
	Title *string `json:"title,omitempty"`
	// The given name (first name) of the `consumer` type recipient should be at least two characters and cannot contain
	// only numbers.
	GivenName *string `json:"givenName,omitempty"`
	// The given name (last name) of the `consumer` type recipient should be at least two characters and cannot contain
	// only numbers.
	FamilyName *string `json:"familyName,omitempty"`
	// The trading name of the `business` type recipient.
	OrganizationName *string `json:"organizationName,omitempty"`
	// The Chamber of Commerce number of the organization for a `business` type recipient. Either this or `vatNumber`
	// has to be provided.
	OrganizationNumber *string `json:"organizationNumber,omitempty"`
	// The VAT number of the organization for a `business` type recipient. Either this or `organizationNumber`
	// has to be provided.
	VatNumber *string `json:"vatNumber,omitempty"`
	// The email address of the recipient.
	//
	// If the domain contains non-ASCII characters, encode it as Punycode per [RFC 3492](https://www.rfc-editor.org/rfc/rfc3492).
	Email string `json:"email"`
	// The phone number of the recipient.
	Phone *string `json:"phone,omitempty"`
	// A street and street number.
	StreetAndNumber string `json:"streetAndNumber"`
	// Any additional addressing details, for example an apartment number.
	StreetAdditional *string `json:"streetAdditional,omitempty"`
	// A postal code.
	PostalCode string `json:"postalCode"`
	// The recipient's city.
	City string `json:"city"`
	// The recipient's region.
	Region *string `json:"region,omitempty"`
	// A country code in [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) format.
	Country string                      `json:"country"`
	Locale  SalesInvoiceRecipientLocale `json:"locale"`
}

func (s *SalesInvoiceRecipient) GetType() SalesInvoiceRecipientType {
	if s == nil {
		return SalesInvoiceRecipientType("")
	}
	return s.Type
}

func (s *SalesInvoiceRecipient) GetTitle() *string {
	if s == nil {
		return nil
	}
	return s.Title
}

func (s *SalesInvoiceRecipient) GetGivenName() *string {
	if s == nil {
		return nil
	}
	return s.GivenName
}

func (s *SalesInvoiceRecipient) GetFamilyName() *string {
	if s == nil {
		return nil
	}
	return s.FamilyName
}

func (s *SalesInvoiceRecipient) GetOrganizationName() *string {
	if s == nil {
		return nil
	}
	return s.OrganizationName
}

func (s *SalesInvoiceRecipient) GetOrganizationNumber() *string {
	if s == nil {
		return nil
	}
	return s.OrganizationNumber
}

func (s *SalesInvoiceRecipient) GetVatNumber() *string {
	if s == nil {
		return nil
	}
	return s.VatNumber
}

func (s *SalesInvoiceRecipient) GetEmail() string {
	if s == nil {
		return ""
	}
	return s.Email
}

func (s *SalesInvoiceRecipient) GetPhone() *string {
	if s == nil {
		return nil
	}
	return s.Phone
}

func (s *SalesInvoiceRecipient) GetStreetAndNumber() string {
	if s == nil {
		return ""
	}
	return s.StreetAndNumber
}

func (s *SalesInvoiceRecipient) GetStreetAdditional() *string {
	if s == nil {
		return nil
	}
	return s.StreetAdditional
}

func (s *SalesInvoiceRecipient) GetPostalCode() string {
	if s == nil {
		return ""
	}
	return s.PostalCode
}

func (s *SalesInvoiceRecipient) GetCity() string {
	if s == nil {
		return ""
	}
	return s.City
}

func (s *SalesInvoiceRecipient) GetRegion() *string {
	if s == nil {
		return nil
	}
	return s.Region
}

func (s *SalesInvoiceRecipient) GetCountry() string {
	if s == nil {
		return ""
	}
	return s.Country
}

func (s *SalesInvoiceRecipient) GetLocale() SalesInvoiceRecipientLocale {
	if s == nil {
		return SalesInvoiceRecipientLocale("")
	}
	return s.Locale
}
