// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SalesInvoiceEmailDetails struct {
	// The subject of the email to be sent.
	Subject string `json:"subject"`
	// The body of the email to be sent. To add newline characters, you can use `\n`.
	Body string `json:"body"`
}

func (s *SalesInvoiceEmailDetails) GetSubject() string {
	if s == nil {
		return ""
	}
	return s.Subject
}

func (s *SalesInvoiceEmailDetails) GetBody() string {
	if s == nil {
		return ""
	}
	return s.Body
}
