// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SessionSequenceTypeResponse string

const (
	SessionSequenceTypeResponseOneoff SessionSequenceTypeResponse = "oneoff"
	SessionSequenceTypeResponseFirst  SessionSequenceTypeResponse = "first"
)

func (e SessionSequenceTypeResponse) ToPointer() *SessionSequenceTypeResponse {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SessionSequenceTypeResponse) IsExact() bool {
	if e != nil {
		switch *e {
		case "oneoff", "first":
			return true
		}
	}
	return false
}
