// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: f3e3c903210a

package components

import (
	"encoding/json"
	"fmt"
)

// SessionRequiredCustomerDetails - Customer details that should be collected during checkout.
type SessionRequiredCustomerDetails string

const (
	SessionRequiredCustomerDetailsEmail           SessionRequiredCustomerDetails = "email"
	SessionRequiredCustomerDetailsBillingAddress  SessionRequiredCustomerDetails = "billing-address"
	SessionRequiredCustomerDetailsShippingAddress SessionRequiredCustomerDetails = "shipping-address"
)

func (e SessionRequiredCustomerDetails) ToPointer() *SessionRequiredCustomerDetails {
	return &e
}
func (e *SessionRequiredCustomerDetails) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "email":
		fallthrough
	case "billing-address":
		fallthrough
	case "shipping-address":
		*e = SessionRequiredCustomerDetails(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SessionRequiredCustomerDetails: %v", v)
	}
}
