// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// SettlementStatus - The status of the settlement.
type SettlementStatus string

const (
	SettlementStatusOpen    SettlementStatus = "open"
	SettlementStatusPending SettlementStatus = "pending"
	SettlementStatusPaidout SettlementStatus = "paidout"
	SettlementStatusFailed  SettlementStatus = "failed"
)

func (e SettlementStatus) ToPointer() *SettlementStatus {
	return &e
}
