// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: dd72f7d081df

package components

type SubGroup struct {
	// In v2 endpoints, monetary amounts are represented as objects with a `currency` and `value` field.
	Amount    *Amount      `json:"amount,omitempty"`
	Subtotals []SubTotals2 `json:"subtotals,omitempty"`
}

func (s *SubGroup) GetAmount() *Amount {
	if s == nil {
		return nil
	}
	return s.Amount
}

func (s *SubGroup) GetSubtotals() []SubTotals2 {
	if s == nil {
		return nil
	}
	return s.Subtotals
}
