// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SubGroup struct {
	// In v2 endpoints, monetary amounts are represented as objects with a `currency` and `value` field.
	Amount    *Amount               `json:"amount,omitempty"`
	Subtotals []ComponentsSubTotals `json:"subtotals,omitempty"`
}

func (o *SubGroup) GetAmount() *Amount {
	if o == nil {
		return nil
	}
	return o.Amount
}

func (o *SubGroup) GetSubtotals() []ComponentsSubTotals {
	if o == nil {
		return nil
	}
	return o.Subtotals
}
