// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// SubscriptionMethodResponse - The payment method used for this subscription. If omitted, any of the customer's valid mandates may be used.
type SubscriptionMethodResponse string

const (
	SubscriptionMethodResponseCreditcard  SubscriptionMethodResponse = "creditcard"
	SubscriptionMethodResponseDirectdebit SubscriptionMethodResponse = "directdebit"
	SubscriptionMethodResponsePaypal      SubscriptionMethodResponse = "paypal"
)

func (e SubscriptionMethodResponse) ToPointer() *SubscriptionMethodResponse {
	return &e
}
