// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/mollie/mollie-api-golang/models/components"
	"github.com/mollie/mollie-api-golang/models/operations"
)

// ListAllChargebacksNotFoundHalJSONError - An error response object.
type ListAllChargebacksNotFoundHalJSONError struct {
	// The status code of the error message. This is always the same code as the status code of the HTTP message itself.
	Status int64 `json:"status"`
	// The HTTP reason phrase of the error. For example, for a `404` error, the `title` will be `Not Found`.
	Title string `json:"title"`
	// A detailed human-readable description of the error that occurred.
	Detail string `json:"detail"`
	// If the error was caused by a value provided by you in a specific field, the `field` property will contain the name
	// of the field that caused the issue.
	Field    *string                                    `json:"field,omitempty"`
	Links    operations.ListAllChargebacksNotFoundLinks `json:"_links"`
	HTTPMeta components.HTTPMetadata                    `json:"-"`
}

var _ error = &ListAllChargebacksNotFoundHalJSONError{}

func (e *ListAllChargebacksNotFoundHalJSONError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// ListAllChargebacksBadRequestHalJSONError - An error response object.
type ListAllChargebacksBadRequestHalJSONError struct {
	// The status code of the error message. This is always the same code as the status code of the HTTP message itself.
	Status int64 `json:"status"`
	// The HTTP reason phrase of the error. For example, for a `404` error, the `title` will be `Not Found`.
	Title string `json:"title"`
	// A detailed human-readable description of the error that occurred.
	Detail string `json:"detail"`
	// If the error was caused by a value provided by you in a specific field, the `field` property will contain the name
	// of the field that caused the issue.
	Field    *string                                      `json:"field,omitempty"`
	Links    operations.ListAllChargebacksBadRequestLinks `json:"_links"`
	HTTPMeta components.HTTPMetadata                      `json:"-"`
}

var _ error = &ListAllChargebacksBadRequestHalJSONError{}

func (e *ListAllChargebacksBadRequestHalJSONError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
