// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/mollie/mollie-api-golang/models/components"
	"github.com/mollie/mollie-api-golang/models/operations"
)

// ListSubscriptionsNotFoundHalJSONError - An error response object.
type ListSubscriptionsNotFoundHalJSONError struct {
	// The status code of the error message. This is always the same code as the status code of the HTTP message itself.
	Status int64 `json:"status"`
	// The HTTP reason phrase of the error. For example, for a `404` error, the `title` will be `Not Found`.
	Title string `json:"title"`
	// A detailed human-readable description of the error that occurred.
	Detail string `json:"detail"`
	// If the error was caused by a value provided by you in a specific field, the `field` property will contain the name
	// of the field that caused the issue.
	Field    *string                                   `json:"field,omitempty"`
	Links    operations.ListSubscriptionsNotFoundLinks `json:"_links"`
	HTTPMeta components.HTTPMetadata                   `json:"-"`
}

var _ error = &ListSubscriptionsNotFoundHalJSONError{}

func (e *ListSubscriptionsNotFoundHalJSONError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// ListSubscriptionsBadRequestHalJSONError - An error response object.
type ListSubscriptionsBadRequestHalJSONError struct {
	// The status code of the error message. This is always the same code as the status code of the HTTP message itself.
	Status int64 `json:"status"`
	// The HTTP reason phrase of the error. For example, for a `404` error, the `title` will be `Not Found`.
	Title string `json:"title"`
	// A detailed human-readable description of the error that occurred.
	Detail string `json:"detail"`
	// If the error was caused by a value provided by you in a specific field, the `field` property will contain the name
	// of the field that caused the issue.
	Field    *string                                     `json:"field,omitempty"`
	Links    operations.ListSubscriptionsBadRequestLinks `json:"_links"`
	HTTPMeta components.HTTPMetadata                     `json:"-"`
}

var _ error = &ListSubscriptionsBadRequestHalJSONError{}

func (e *ListSubscriptionsBadRequestHalJSONError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
