// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/mollie/mollie-api-golang/models/components"
	"github.com/mollie/mollie-api-golang/models/operations"
)

// UpdateProfileUnprocessableEntityHalJSONError - An error response object.
type UpdateProfileUnprocessableEntityHalJSONError struct {
	// The status code of the error message. This is always the same code as the status code of the HTTP message itself.
	Status int64 `json:"status"`
	// The HTTP reason phrase of the error. For example, for a `404` error, the `title` will be `Not Found`.
	Title string `json:"title"`
	// A detailed human-readable description of the error that occurred.
	Detail string `json:"detail"`
	// If the error was caused by a value provided by you in a specific field, the `field` property will contain the name
	// of the field that caused the issue.
	Field    *string                                          `json:"field,omitempty"`
	Links    operations.UpdateProfileUnprocessableEntityLinks `json:"_links"`
	HTTPMeta components.HTTPMetadata                          `json:"-"`
}

var _ error = &UpdateProfileUnprocessableEntityHalJSONError{}

func (e *UpdateProfileUnprocessableEntityHalJSONError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// UpdateProfileGoneHalJSONError - An error response object.
type UpdateProfileGoneHalJSONError struct {
	// The status code of the error message. This is always the same code as the status code of the HTTP message itself.
	Status int64 `json:"status"`
	// The HTTP reason phrase of the error. For example, for a `404` error, the `title` will be `Not Found`.
	Title string `json:"title"`
	// A detailed human-readable description of the error that occurred.
	Detail string `json:"detail"`
	// If the error was caused by a value provided by you in a specific field, the `field` property will contain the name
	// of the field that caused the issue.
	Field    *string                           `json:"field,omitempty"`
	Links    operations.UpdateProfileGoneLinks `json:"_links"`
	HTTPMeta components.HTTPMetadata           `json:"-"`
}

var _ error = &UpdateProfileGoneHalJSONError{}

func (e *UpdateProfileGoneHalJSONError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// UpdateProfileNotFoundHalJSONError - An error response object.
type UpdateProfileNotFoundHalJSONError struct {
	// The status code of the error message. This is always the same code as the status code of the HTTP message itself.
	Status int64 `json:"status"`
	// The HTTP reason phrase of the error. For example, for a `404` error, the `title` will be `Not Found`.
	Title string `json:"title"`
	// A detailed human-readable description of the error that occurred.
	Detail string `json:"detail"`
	// If the error was caused by a value provided by you in a specific field, the `field` property will contain the name
	// of the field that caused the issue.
	Field    *string                               `json:"field,omitempty"`
	Links    operations.UpdateProfileNotFoundLinks `json:"_links"`
	HTTPMeta components.HTTPMetadata               `json:"-"`
}

var _ error = &UpdateProfileNotFoundHalJSONError{}

func (e *UpdateProfileNotFoundHalJSONError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
